---
title: "Least Squares"
author: "CDS DS-121<br>Boston University"
format: 
    revealjs:
        math: true
        css: 
        - styles.css
        html-math-method: mathjax
        highlight-style: github
        slide-number: true
        show-slide-number: all
        chalkboard: true
---

## Learning Objectives

:::{style="font-size: .8em"}

- Normal equations
    - with multiple solutions
    - with a unique solution
- Projections into a high-dimensional subspace with any basis
- Linear regression
    - simple
    - multiple
:::

## Normal Equations

:::{style="font-size: .8em"}
The normal equations _**always**_ have a solution.  
</br>

However, the solution does not have to be unique. There can be multiple solutions that all minimize $\Vert A\mathbf{x} - \mathbf{b}\Vert.$

</br>

We know that a linear system has multiple solutions when there are columns that are not pivot columns. Equivalently, when $A \bf{\hat{x}} = \bf{\hat{b}}$ has multiple solutions, the columns of $A$ are linearly dependent.
:::

## Normal Equations

:::{style="font-size: .8em"}

In the figure below, $A$ is $3 \times 3$. Note that $\operatorname{Col}A$ is only two-dimensional because the three columns are linearly dependent.

:::{.center-text}
```{python}
#
import laUtilities as ut
import numpy as np
import matplotlib.pyplot as plt

qr_setting = None

fig = ut.three_d_figure((9, 7), 'Multiple Solutions to the Normal Equations', 
                        -15, 15, -15, 15, -15, 15, (4,4), qr = qr_setting)
a2 = np.array([5.0,-13.0,-3.0])
a1 = np.array([1,-2.0,3])
a3 = -2*a1 + a2
b = np.array([6.0, 8.0, -5.0])
A = np.array([a1, a2]).T
bhat = A.dot(np.linalg.inv(A.T.dot(A))).dot(A.T).dot(b)
fig.text(a1[0], a1[1], a1[2], r'$\bf a_1$', 'a_1', size=20)
fig.text(a2[0], a2[1], a2[2], r'$\bf a_2$', 'a_2', size=20)
fig.text(a3[0], a3[1], a3[2], r'$\bf a_3$','a_3', size=20)
fig.text(b[0], b[1], b[2], r'$\bf b$', 'b', size=20)
fig.text(bhat[0], bhat[1], bhat[2], r'$A\mathbf{\hat{x}} = \mathbf{\hat{b}}$', 'b-hat', size=20)
#ax.text(1,-4,-10,r'Span{$\bf a,b$}',size=16)
#ax.text(0.2,0.2,-4,r'$\bf 0$',size=20)
# plotting the span of v
fig.plotSpan(a1, a2, 'Green')
fig.plotPoint(a1[0], a1[1], a1[2], 'r')
fig.plotPoint(a2[0], a2[1], a2[2], 'r')
fig.plotPoint(a3[0], a3[1], a3[2], 'r')
fig.plotPoint(b[0], b[1], b[2], 'b')
fig.plotPoint(bhat[0], bhat[1], bhat[2], 'b')
fig.plotLine([b, bhat], 'b', '--')
#ut.plotPoint3d(ax,0,0,0,'b')
fig.ax.view_init(azim=26.0,elev=-77.0)
```
:::


The orthogonal projection $\hat{\mathbf{b}}$ is always unique. Some least squares problem have multiple solutions, because there are _**multiple ways**_ to construct $\hat{\mathbf{b}}$.

::: 

## Normal Equations

:::{style="font-size:.8em"}

Let's find a least-squares solution for $A\mathbf{x} = \mathbf{b}$ for
:::

:::{style="font-size:.6em"}
$$
A = \begin{bmatrix}1&1&0&0\\1&1&0&0\\1&0&1&0\\1&0&1&0\\1&0&0&1\\1&0&0&1\end{bmatrix},\;\;\; \mathbf{b} = \begin{bmatrix}-3\\-1\\0\\2\\5\\1\end{bmatrix}.
$$
:::

:::{style="font-size:.8em"}
We compute the components of the normal equations.
:::

:::{style="font-size:.6em"}
$$
A^{\top} A = \begin{bmatrix}1&1&1&1&1&1\\1&1&0&0&0&0\\0&0&1&1&0&0\\0&0&0&0&1&1\end{bmatrix}\begin{bmatrix}1&1&0&0\\1&1&0&0\\1&0&1&0\\1&0&1&0\\1&0&0&1\\1&0&0&1\end{bmatrix} = \begin{bmatrix}6&2&2&2\\2&2&0&0\\2&0&2&0\\2&0&0&2\end{bmatrix},
$$
:::

## Normal Equations

:::{style="font-size:.6em"}

$$
A^{\top} \mathbf{b} = \begin{bmatrix}1&1&1&1&1&1\\1&1&0&0&0&0\\0&0&1&1&0&0\\0&0&0&0&1&1\end{bmatrix}\begin{bmatrix}-3\\-1\\0\\2\\5\\1\end{bmatrix} = \begin{bmatrix}4\\-4\\2\\6\end{bmatrix}.
$$
:::

:::{style="font-size:.8em"}
To solve $A^{\top} A\hat{\mathbf{x}} = A^{\top} \mathbf{b},$ we'll use row reduction.  The augmented matrix $[A^{\top} A \vert A^{\top} \mathbf{b}]$ is:
:::

:::{style="font-size:.6em"}
$$
\left[\begin{array}{cccc|c}6&2&2&2&4\\2&2&0&0&-4\\2&0&2&0&2\\2&0&0&2&6\end{array}\right] \sim \left[\begin{array}{cccc|c}1&0&0&1&3\\0&1&0&-1&-5\\0&0&1&-1&-2\\0&0&0&0&0\end{array}\right]
$$
:::

:::{style="font-size:.8em"}

In the RREF, there are only 3 pivot columns, so there is a free variable.
:::

## Normal Equations

:::{style="font-size:.8em"}
From the RREF we see that only the first three columns of $A^\top A$ are linearly independent. The last column can be written as a linear combination of them.

<br>

The columns of $A^\top A$ are linearly dependent, because the columns of $A$ are linearly dependent.

<br>

You can see this as follows: if $A$ has a non-trivial null space, then $A^\top A$ also has a nontrival null space.
:::

## Normal Equations

:::{style="font-size:.8em"}
The general solution of the normal equations is $x_1 = 3-x_4,$ $x_2 = -5+x_4,$ $x_3 = -2 + x_4,$ and $x_4$ is free.

<br>

Hence, the general least-squares solution of $A\hat{\mathbf{x}} = \mathbf{b}$ has the form

$$
\mathbf{\hat{x}} = \begin{bmatrix}3\\-5\\-2\\0\end{bmatrix} + x_4\begin{bmatrix}-1\\1\\1\\1\end{bmatrix}.
$$
:::

## Normal Equations

:::{style="font-size:.8em"}

Here is a theorem that allows us to identify when there are multiple least-squares solutions.

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p><span class="label">Theorem</span>
        Let \(A\) be an \(m\times n\) matrix.  The following statements are equivalent:
<ol start=1>
<li> The equation \(A\mathbf{x} = \mathbf{b}\) has a unique least-squares solution for each \(\mathbf{b}\) in \(\mathbb{R}^m.\)</li>
<li>The columns of \(A\) are linearly independent.</li>
<li>The matrix \(A^\top A\) is invertible.</li>

When these statements are true, the least-squares solution \(\mathbf{\hat{x}}\) is given by:

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\(\mathbf{\hat{x}} = (A^\top A)^{-1}A^\top \mathbf{b}.\)
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

:::

## Projection Using Any Basis

:::{style="font-size: .8em"}
When $A^\top A$ is invertible, we can put together the two equations
$\mathbf{\hat{x}} = (A^\top A)^{-1}A^\top \mathbf{b}$ and $A\mathbf{\hat{x}} = \hat{\mathbf{b}}$ to get:

$$
\hat{\mathbf{b}} = A(A^\top A)^{-1}A^\top \mathbf{b}.
$$

Let's stop and look at this another way.  Up until now we have seen how to project a point onto a line, or on to a subspace with an orthogonal basis.  

<br>

This equation shows how to project onto a subspace (namely $\operatorname{Col} A$) given an _**arbitrary**_ basis.  This is a general formula that can be very useful.
::: 

## Simple Regression 

:::{style="font-size: .8em"}
Let's imagine for a moment a data set where the data fit a line perfectly.

Then, if each of the data points happened to fall exactly on the line, the parameters $\beta_0$ and $\beta_1$ would satisfy the equations:

$$
\beta_0 + \beta_1 x_1 = y_1 
$$
$$
\beta_0 + \beta_1 x_2 = y_2 
$$
$$
\beta_0 + \beta_1 x_3 = y_3 
$$
$$
\vdots
$$

$$
\beta_0 + \beta_1 x_n = y_n
$$
:::


## Simple Regression 

:::{style="font-size: .8em"}
We can write this system as the following matrix equation:

$$
X\mathbf{\beta} = \mathbf{y},
$$ 

$$
X=\begin{bmatrix}1&x_1\\1&x_2\\\vdots&\vdots\\1&x_n\end{bmatrix},\;\;\mathbf{\beta} = \begin{bmatrix}\beta_0\\\beta_1\end{bmatrix},\;\;\mathbf{y}=\begin{bmatrix}y_1\\y_2\\\vdots\\y_n\end{bmatrix}.
$$

* The independent variables are collected into the __design matrix__ $X.$
* The dependent variables are collected into an __observation__ vector $\mathbf{y}.$
* The parameters of the model are collected into a __parameter__ vector $\beta.$
:::


## Simple Regression 

:::{style="font-size: .8em"}
If the data points don't actually lie exactly on a line: 

there are no parameters $\beta_0, \beta_1$ for which the predicted $y$-values in $X\mathbf{\beta}$ equal the observed $y$-values in $\mathbf{y}$. Also, $X\mathbf{\beta}=\mathbf{y}$ has no solution.

<br>

When the data doesn't fall exactly on a line, seek the $\beta$ that minimizes the sum of squared residuals, i.e.,

$$
\sum_i ((\beta_0 + \beta_1 x_i) - y_i)^2 =\Vert X\beta -\mathbf{y}\Vert^2
$$

:::{.center-text style="font-size: 1.1em"}
_The sum of squares of the residuals is exactly the square of the distance between the vectors $X\mathbf{\beta}$ and $\mathbf{y}.$_
:::
:::

## Simple Regression 

:::{style="font-size: .8em"}
This is a least-squares problem, $A\mathbf{x} = \mathbf{b},$ just with different notation. That is, computing the least-squares solution of $X\mathbf{\beta} = \mathbf{y}$ is equivalent to finding the $\mathbf{\beta}$ that determines the least-squares line.

:::{.center-text}
```{python}
#
ax = ut.plotSetup(-10, 10, -10, 10, size = (6, 5))
ut.centerAxes(ax)
line = np.array([1, 0.5])
xlin = -10.0 + 20.0 * np.random.random(100)
ylin = line[0]+ (line[1] * xlin) + np.random.normal(scale = 1.5, size = 100)
ax.plot(xlin, ylin, 'ro', markersize=6)
ax.plot(xlin, line[0] + line[1] * xlin, 'b-')
plt.text(-9,3,r'$y = \beta_0 + \beta_1x$',size=20);
```
:::
:::

## Simple Regression 

:::{style="font-size: .8em"}
:::{.columns}

:::{.column}
__Example 1.__  Find the equation $y = \beta_0 + \beta_1 x$ of the least-squares line that best fits:

:::{.center-text}
| x | y |
|---|---|
| 2 | 1 |
| 5 | 2 |
| 7 | 3 |
| 8 | 3 |
:::
:::

:::{.column}
```{python}
#
ax = ut.plotSetup(0, 10, 0, 3.5, size = (7, 6))
ut.centerAxes(ax)
pts = np.array([[2,1], [5,2], [7,3], [8,3]]).T
ax.plot(pts[0], pts[1], 'ro', markersize = 10);
plt.xlabel('x', size = 20)
plt.ylabel('y', size = 20);
```
:::
:::
:::

## Simple Regression 

:::{style="font-size: .8em"}
__Solution.__ Use the $x$-coordinates of the data to build the design matrix $X$, and the $y$-coordinates to build the observation vector $\mathbf{y}$:

$$
X = \begin{bmatrix}1&2\\1&5\\1&7\\1&8\end{bmatrix},\;\;\;\mathbf{y}=\begin{bmatrix}1\\2\\3\\3\end{bmatrix}
$$


To obtain the least-squares line, find the least-squares solution to $X\mathbf{\beta} = \mathbf{y}.$

<br>

We do this by solving the __normal equation__ with new notation:

$$
X^\top X\mathbf{\beta} = X^\top \mathbf{y}.
$$
:::

## Simple Regression 

:::{style="font-size: .8em"}
$$
X^\top X = \begin{bmatrix}1&1&1&1\\2&5&7&8\end{bmatrix}\begin{bmatrix}1&2\\1&5\\1&7\\1&8\end{bmatrix} = \begin{bmatrix}4&22\\22&142\end{bmatrix},
$$

$$
X^\top \mathbf{y} =  \begin{bmatrix}1&1&1&1\\2&5&7&8\end{bmatrix}\begin{bmatrix}1\\2\\3\\3\end{bmatrix} = \begin{bmatrix}9\\57\end{bmatrix}.
$$

The normal equations are: $\begin{bmatrix}4&22\\22&142\end{bmatrix}\begin{bmatrix}\beta_0\\\beta_1\end{bmatrix} = \begin{bmatrix}9\\57\end{bmatrix}.$

:::

## Simple Regression 

:::{style="font-size: .8em"}
Solving, we get:
    
$$
\begin{bmatrix}\beta_0\\\beta_1\end{bmatrix}=\begin{bmatrix}4&22\\22&142\end{bmatrix}^{-1}\begin{bmatrix}9\\57\end{bmatrix}
$$

$$
= \frac{1}{84}\begin{bmatrix}142&-22\\-22&4\end{bmatrix}\begin{bmatrix}9\\57\end{bmatrix}
$$

$$
= \begin{bmatrix}2/7\\5/14\end{bmatrix}.
$$
:::

## Simple Regression 

:::{style="font-size: .8em"}
So the least-squares line has the equation $y = \frac{2}{7} + \frac{5}{14}x.$

:::{.center-text}
```{python}
#
ax = ut.plotSetup(0, 10, 0, 4, size = (5, 5))
ut.centerAxes(ax)
pts = np.array([[2,1], [5,2], [7,3], [8,3]]).T
ax.plot(pts[0], pts[1], 'ro', markersize = 10)
ut.plotLinEqn(-5./14, 1, 2./7, color='b')
plt.text(6,1.5, r'$y = \frac{2}{7} + \frac{5}{14}x$', size=24);
```
:::
:::

## Simple Regression 

:::{style="font-size: .8em"}

```{python}
#
quad = np.array([1, 3, 0.5])
xquad = -10.0 + 20.0 * np.random.random(100)
yquad = quad[0] + (quad[1] * xquad) + (quad[2] * xquad * xquad) + np.random.normal(scale = 1.5, size = 100)
```

Regression can also be used when data points $\small(x_1, y_1), \dots, (x_n, y_n)$ appear to lie along some sort of parabola instead of a straight line.  Suppose we wish to approximate the data by an equation of the form

$$\small
y = \beta_0 + \beta_1x + \beta_2x^2.
$$


This system can be written as a matrix equation of the form $\small \mathbf{y} = X\mathbf{\beta}:$

$$\small
\begin{bmatrix}y_1\\y_2\\\vdots\\y_n\end{bmatrix} = \begin{bmatrix}1&x_1&x_1^2\\1&x_2&x_2^2\\\vdots&\vdots&\vdots\\1&x_n&x_n^2\end{bmatrix} \begin{bmatrix}\beta_0\\\beta_1\\\beta_2\end{bmatrix}.
$$

The approach to solve this problem would be exactly the same as with a simpler design matrix.

:::

## Simple Regression
:::{.center-text}
```{python}
#
m = np.shape(xquad)[0]
X = np.array([np.ones(m), xquad,xquad**2]).T
beta = np.linalg.inv(X.T @ X) @ X.T @ yquad
#
ax = ut.plotSetup(-10, 10, -10, 20, size = (10, 7))
ut.centerAxes(ax)
xplot = np.linspace(-10, 10, 50)
yestplot = beta[0] + beta[1]  * xplot + beta[2] * xplot**2
ax.plot(xplot, yestplot, 'b-', lw=2)
ax.plot(xquad, yquad, 'ro', markersize = 8);
```
:::

## Multiple Regression

:::{style="font-size: .8em"}
Suppose an experiment involves two independent variables -- say, $u$ and $v$, -- and one dependent variable, $y$. A linear equation for predicting $y$ from $u$ and $v$ has the form

$$
y = \beta_0 + \beta_1 u + \beta_2 v.
$$


Since there is more than one independent variable, this is called __multiple regression.__

Such system has the form $\mathbf{y} = X\mathbf{\beta}$ where

$$
\mathbf{y} = \begin{bmatrix}y_1\\y_1\\\vdots\\y_n\end{bmatrix},\;\;X = \begin{bmatrix}1&u_1&v_1\\1&u_2&v_2\\\vdots&\vdots&\vdots\\1&u_n&v_n\end{bmatrix},\;\;\mathbf{\beta}=\begin{bmatrix}\beta_0\\\beta_1\\\beta_2\end{bmatrix}.
$$
:::

## Multiple Regression

:::{style="font-size: .8em"}
A more general prediction equation might have the form

$$
y = \beta_0 + \beta_1 u + \beta_2 v + \beta_3 u^2 + \beta_4 uv + \beta_5 v^2
$$

A least squares fit to equations like this is called a __trend surface.__

<br>

In general, a linear model will arise whenever $y$ is to be predicted by an equation of the form

$$y = \beta_0 \: f_0(u,v) + \beta_1 \: f_1(u,v) + \cdots + \beta_k \: f_k(u,v)$$

with $f_0,\dots,f_k$ any sort of known functions and $\beta_0, \ldots,\beta_k$ unknown weights.
:::

## Multiple Regression

:::{.center-text}
```{python}
#
fig = ut.three_d_figure((8, 8), 'multivariate regression example', 
                       -7, 7, -7, 7, -8, 8,
                        equalAxes = False, figsize = (7, 7), qr = qr_setting)
np.random.seed(6)
v = [4.0,  4.0, 2.0]
u = [-4.0, 3.0, 1.0]
npts = 70
# set locations of points that fall within x,y
xc = -7.0 + 14.0 * np.random.random(npts)
yc = -7.0 + 14.0 * np.random.random(npts)
A = np.array([u,v]).T
# project these points onto the plane
P = A @ np.linalg.inv(A.T @ A) @ A.T
coords = P @ np.array([xc,yc,np.zeros(npts)])
coords[2] += np.random.normal(scale = 1, size = npts)
for i in range(coords.shape[-1]):
    fig.plotPoint(coords[0,i],coords[1,i], coords[2,i], 'r')
fig.ax.set_zlabel('y')
fig.ax.set_xlabel('u')
fig.ax.set_ylabel('v')
fig.desc['xlabel'] = 'u'
fig.desc['ylabel'] = 'v'
fig.desc['zlabel'] = 'y'
fig.ax.view_init(azim=30, elev = 15)
```
:::

## Multiple Regression

:::{.center-text}
```{python}
#
fig = ut.three_d_figure((8,8), 'multivariate regression example with fitted plane', 
                       -7, 7, -7, 7, -8, 8,
                        equalAxes = False, figsize = (7, 7), qr = qr_setting)
np.random.seed(6)
v = [4.0,  4.0, 2.0]
u = [-4.0, 3.0, 1.0]
npts = 70
# set locations of points that fall within x,y
xc = -7.0 + 14.0 * np.random.random(npts)
yc = -7.0 + 14.0 * np.random.random(npts)
A = np.array([u,v]).T
# project these points onto the plane
P = A @ np.linalg.inv(A.T @ A) @ A.T
coords = P @ np.array([xc,yc,np.zeros(npts)])
coords[2] += np.random.normal(scale = 1, size = npts)
for i in range(coords.shape[-1]):
    fig.plotPoint(coords[0,i],coords[1,i], coords[2,i], 'r')
fig.ax.set_zlabel('y')
fig.ax.set_xlabel('u')
fig.ax.set_ylabel('v')
fig.desc['xlabel'] = 'u'
fig.desc['ylabel'] = 'v'
fig.desc['zlabel'] = 'y'
fig.plotSpan(u, v, 'Green')
fig.ax.view_init(azim=30, elev = 30)
```
:::

## Multiple Regression

:::{style="font-size: .8em"}
The linear model for multiple regression has the same abstract form as the model for the simple regression.
<!-- 
We can see that there the general principle is the same across all the different kinds of linear models. -->

Once $X$ is defined, the normal equations for $\mathbf{\beta}$ have the same matrix form, no matter how many variables are involved. Thus, for any linear model where $X^{\top} X$ is invertible, the least squares $\hat{\mathbf{\beta}}$ is given by $(X^{\top} X)^{-1}X^{\top} \mathbf{y}$.


```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <span class="label">Theorem</span>
        <p>Let \(X\) be an \(m\times n\) matrix.  The following statements are equivalent:
<ol start=1>
<li>The equation \(X\mathbf{\beta} = \mathbf{y}\) has a unique least-squares solution for each \(\mathbf{y}\) in \(\mathbb{R}^m.\)</li>
<li>The columns of \(X\) are linearly independent.</li>
<li>The matrix \(X^{\top}  X\) is invertible.</li>
</p>
    </div>
    """

html_content = generate_html()
display(HTML(html_content))
```
:::

## Regression in Practice

:::{style="font-size: .8em"}

__Example.__ Say I have a 10 year old car I want to sell. To find the ideal price, I surveyed the prices and ages of cars for sale in my neighborhood.
:::

<br> 

:::{.columns}
:::{.column}
:::{style="font-size: .6em"}
| Car age | Selling price |
|---|---|
| 1 | 23,650 |
| 2 | 19,988 |
| 3 | 20,998 |
| 3 | 20,448 |
| 4 | 15,700 |
| 5 | 25,985 |
| 6 | 16,964 |
:::
:::
:::{.column}
:::{style="font-size: .6em"}
| Car age | Selling price |
|---|---|
| 10 | 15,000 |
| 11 | 11,500 |
| 14 | 7,950 |
| 14 | 9,000 |
| 16 | 3,950 |
| 17 | 5,250 |
:::
:::
:::



## Regression in Practice

:::{style="font-size: .8em"}
```{python}
#| echo: false
ax = ut.plotSetup(0, 20, 0, 27000, size = (12, 6))
ut.centerAxes(ax)
cars = np.array([[1,23650], [2,19988], [3,20998], [3,20448], [4, 15700], [5, 25985], [6, 16964], [10, 15000], [11, 11500], [14, 7950], [14, 9000], [16, 3950], [17, 5250]]).T
ax.plot(cars[0], cars[1], 'ro', markersize = 10);
plt.xlabel('age of car', size = 20)
plt.ylabel('selling price ($)', size = 20);
```
:::

## Regression in Practice

:::{style="font-size: .8em"}
__Solution.__ First we need to set up our design matrix $X$, which contains the independent variable (age), and our observation vector $\mathbf{y}$, which contains our dependent variable (price).

```{python}
#| echo: true
cars = np.array([[1,23650], [2,19988], [3,20998], [3,20448], [4, 15700], [5, 25985], [6, 16964], [10, 15000], [11, 11500], [14, 7950], [14, 9000], [16, 3950], [17, 5250]]).T
prices = cars[1:].T
age = cars[:-1].T

X = np.column_stack([np.ones(age.shape[0], dtype = 'int'), age])

print(X)
```
:::

## Regression in Practice

:::{style="font-size: .8em"}
Now that we have $X$ and $\mathbf{y}$, we want to solve for $\beta$. We can again use the normal equations to do this.

$$
\beta = (X^\top X)^{-1} X^\top \mathbf{y}
$$

<br>

```{python}
#| echo: true
beta_hat = np.linalg.inv(X.T @ X) @ X.T @ prices
print(beta_hat)
```

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
       What does \(\beta\) tell us about car prices?
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```
:::

## Regression in Practice

:::{style="font-size: .8em"}
Using this model, we can estimate prices of cars we did not train the model on. For example, with this model if my car was 10 years old, I might charge \$12,900.

```{python}
#| echo: true
pred_price = beta_hat[0] + beta_hat[1]*10
print(pred_price)
```

```{python}
#| echo: false
ax = ut.plotSetup(0, 20, 0, 25000, size = (12, 3))
ut.centerAxes(ax)
ax.plot(cars[0], cars[1], 'ro', markersize = 10);
#ax.axline([0,beta_hat[0]], [20, beta_hat[0] + beta_hat[1]*20])
ax.plot([0,20], [beta_hat[0], beta_hat[0] + beta_hat[1]*20], '-', label='yhat = y')
plt.xlabel('age of car', size = 20)
plt.ylabel('selling price ($)', size = 20);
```
:::


