---
title: Diagonalization
author: "CDS DS-121<br>Boston University"
format: 
    revealjs:
        math: true
        css: 
        - styles.css
        html-math-method: mathjax
        highlight-style: github
---

## Learning Objectives

:::{style="font-size: .8em"}
Today we will talk about matrix diagonalization.


We will learn how to _diagonalize_ a square matrix, determine when this is even possible, and interpret it geometrically as a change of basis.

In addition, we will study the special properties that arise when diagonalizing a _symmetric_ matrix.
:::

## Diagonalization

:::{style="font-size: .8em"}
Given a _square_ matrix $A$, our goal for today is to find a factorization of $A$ is of the form 

$$
A = PDP^{-1}
$$

where:

- $D$ and $P$ are square matrices of the same size as $A$,
- $P$ is invertible (so that $P^{-1}$ exists), and
- $D$ is a _diagonal_ matrix, meaning that it only has non-zero entries on the diagonal. 
:::

## Diagonalization

:::{style="font-size: .8em"}
Recall that two $n \times n$ matrices $A$ and $B$ are said to be _similar_ if $A = PBP^{-1}.$

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        A square matrix \(A\) is <b>diagonalizable</b> if \(A\) is similar to a diagonal matrix.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

That is, if we can find some invertible $P$ such that

$$
A = PDP^{-1}
$$ 

and $D$ is a diagonal matrix.

<br>

Let's use this factorization to compute $A^k$ quickly for large values of $k$.
:::

## Powers of a Matrix

:::{style="font-size: .8em"}
As a starting point, let's see how simple it is to take powers of a _diagonal_ matrix.

Consider taking the powers of the following diagonal matrix $D = \begin{bmatrix}5&0\\0&3\end{bmatrix}.$ 

$$D^2 = \begin{bmatrix}5&0\\0&3\end{bmatrix}\begin{bmatrix}5&0\\0&3\end{bmatrix} = \begin{bmatrix}5^2&0\\0&3^2\end{bmatrix},$$ 
$$D^3 = DD^2 = \begin{bmatrix}5&0\\0&3\end{bmatrix}\begin{bmatrix}5^2&0\\0&3^2\end{bmatrix} = \begin{bmatrix}5^3&0\\0&3^3\end{bmatrix}.$$

In general, $D^k = \begin{bmatrix}5^k&0\\0&3^k\end{bmatrix} \;\;\;\mbox{for}\;k\geq1.$
:::

## Powers of a Matrix

:::{style="font-size: .8em"}

Let's extend this idea to a _diagonalizable_ matrix $A$.

 __Example.__ Let $A = \begin{bmatrix}7&2\\-4&1\end{bmatrix}.$ Find a formula for $A^k$. Use the fact that
:::

:::{style="font-size: .6em"}
$$
A = \underbrace{\begin{bmatrix}1&1\\-1&-2\end{bmatrix}}_{P} \underbrace{\begin{bmatrix}5&0\\0&3\end{bmatrix}}_{D} \underbrace{\begin{bmatrix}2&1\\-1&-1\end{bmatrix}}_{P^{-1}}.
$$
:::
<!-- 
which we show below using `Python` -->

:::{style="font-size: .8em"}
```{python}
import numpy as np
```

```{python}
#| echo: true
P = np.array([[ 1,  1],
              [-1, -2]])
D = np.array([[ 5,  0],
              [ 0,  3]])
Pinv = np.array([[ 2,  1],
                 [-1, -1]])
assert(np.allclose(Pinv, np.linalg.inv(P))) # check that P and Pinv are inverses
print(P @ D @ Pinv)                         # calculate A = P D P^{-1}
```
:::

## Powers of a Matrix

:::{style="font-size: .8em"}
__Solution.__  By associativity of matrix multiplication,

$$
\begin{align*}
A^2 &= (PDP^{-1})(PDP^{-1}) \\
&= PD(P^{-1}P)DP^{-1} \\
&= PDDP^{-1} \\
&= PD^2P^{-1}
\end{align*}
$$

$$
= \begin{bmatrix}1&1\\-1&-2\end{bmatrix}\begin{bmatrix}5^2&0\\0&3^2\end{bmatrix}\begin{bmatrix}2&1\\-1&-1\end{bmatrix}
$$

The same pattern occurs for $A^3$, $A^4$, and so on. In general, for $k\geq 1,$

$$
A^k = PD^kP^{-1}.
$$

<!-- For this particular matrix $A$, we find that

$$
\begin{align*}
A^k &= P D^k P^{-1} \\
&=\begin{bmatrix}1&1\\-1&-2\end{bmatrix}\begin{bmatrix}5^k&0\\0&3^k\end{bmatrix}\begin{bmatrix}2&1\\-1&-1\end{bmatrix} \\
&=\begin{bmatrix}2\cdot5^k-3^k&5^k-3^k\\2\cdot3^k-2\cdot5^k&2\cdot3^k-5^k\end{bmatrix}.
\end{align*}
$$ -->
:::



## Diagonalization Theorem

:::{style="font-size: 0.8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        <span class="label">
        The Diagonalization Theorem</span>
        An \(n\times n\) matrix \(A\) is diagonalizable if and only if \(A\) has \(n\) linearly independent eigenvectors.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

In fact, if there are $n$ linearly independent eigenvectors, then we can write $A = PDP^{-1}$ where:

- The columns of $P$ are the $n$ linearly independent eigenvectors of $A$.
- The diagonal entries of $D$ are eigenvalues of $A$ that correspond, respectively, to the eigenvectors in $P$.

This is the __eigendecomposition__ of $A$.
<!-- <br>

In other words, $A$ is diagonalizable if and only if there are enough eigenvectors to form a basis of $\mathbb{R}^n$.  
 
 <br>

We call such a basis an __eigenvector basis__ or an __eigenbasis__ of $\mathbb{R}^n$. -->
:::

<!-- ## The Need for Eigenvectors and Eigenvalues{.really-really-smaller-title}


<br>

__Example.__ A $2 \times 2$ rotation matrix like

$$
\begin{bmatrix}
0 & -1 \\
1 & 0
\end{bmatrix}
$$

is not diagonalizable, because we saw last week that it does not have any (real-valued) eigenvalues. -->

## Diagonalization Theorem

:::{style="font-size: 0.8em"}
__Proof ($\Rightarrow$ direction).__

> If $A$ is diagonalizable, then it has $n$ linearly independent eigenvectors.
<br>

Since $A$ is assumed to be diagonalizable, it is possible to write $A$ in the form $A = PDP^{-1}$. If we right-multiply both sides of this equation by $P$, we find that

$$
AP = PD.
$$

<br>

It is given that $P$ is invertible, which means that its columns must be linearly independent (by the IMT).
:::

## Diagonalization Theorem

:::{style="font-size: 0.8em"}

Observe that if $P$ is any $n\times n$ matrix with columns $\mathbf{v}_1,\dots,\mathbf{v}_n,$ then

$$
AP = A[\mathbf{v}_1\;\mathbf{v}_2\;\cdots\;\mathbf{v}_n] = [A\mathbf{v}_1\;A\mathbf{v}_2\;\cdots\;A\mathbf{v}_n].
$$

Next, note if $D$ is any diagonal matrix with diagonal entries $\lambda_1,\dots,\lambda_n,$ then

$$
PD =
[\mathbf{v}_1\;\mathbf{v}_2\;\cdots\;\mathbf{v}_n]
\begin{bmatrix}\lambda_1&0&\cdots&0\\0&\lambda_2&\cdots&0\\\vdots&\vdots&\ddots&\vdots\\0&0&\cdots&\lambda_n\end{bmatrix}
= [\lambda_1\mathbf{v}_1\;\lambda_2\mathbf{v}_2\;\cdots\;\lambda_n\mathbf{v}_n].
$$

Since $AP = PD$, we find $[A\mathbf{v}_1\;A\mathbf{v}_2\;\cdots\;A\mathbf{v}_n] = [\lambda_1\mathbf{v}_1\;\lambda_2\mathbf{v}_2\;\cdots\;\lambda_n\mathbf{v}_n].$
:::

## Diagonalization Theorem

:::{style="font-size: 0.8em"}

That is,

$$
A\mathbf{v}_1 = \lambda_1\mathbf{v}_1, \;\;\; A\mathbf{v}_2 = \lambda_2\mathbf{v}_2, \;\;\; \dots, \;\;\; A\mathbf{v}_n = \lambda_n\mathbf{v}_n.
$$

Because $A{\bf v_i}$ is scaling ${\bf v_i}$ by $\lambda_i$, we know ${\bf v_i}$ must be an eigenvector of $A$ and $\lambda_i$ must be its corresponding eigenvalue.

<br>

Hence, the columns of $P$ are eigenvectors of $A$. Additionally, we already showed that the columns of $P$ are linearly independent by the IMT.

<br>

Therefore, if $A$ is diagonalizable, then it has $n$ linearly independent eigenvectors.
:::

## Diagonalization Theorem

:::{style="font-size: 0.8em"}

__Proof ($\Leftarrow$ direction).__

> If $A$ has $n$ linearly independent eigenvectors, then $A$ is diagonalizable.

Using the ideas from the first half of the proof, we construct the diagonalization of $A$ as follows.

- Let $P$ be a matrix whose columns are the $n$ linearly independent eigenvectors of $A$.
- Let $D$ be a diagonal matrix whose diagonal entries are the corresponding eigenvalues $\lambda_1, \dots, \lambda_n$.
:::

## Diagonalization Theorem

:::{style="font-size: 0.8em"}
Using the sequence of equations from earlier in reverse order, we can go from 

$$
A\mathbf{v}_1 = \lambda_1\mathbf{v}_1, \;\;\; A\mathbf{v}_2 = \lambda_2\mathbf{v}_2, \;\;\; \dots, \;\;\; A\mathbf{v}_n = \lambda_n\mathbf{v}_n
$$

to 

$$
AP = PD.
$$

Since the eigenvectors are given as linearly independent, $P$ is invertible (by the IMT) and so 

$$
A = PDP^{-1}.
$$
:::

<!-- ## The Need for Eigenvectors and Eigenvalues{.really-really-smaller-title}

:::{style="font-size: 1.2em"}
The takeaway is this:

<br>

Every $n\times n$ matrix having $n$ **linearly independent** eigenvectors can be factored into the product of 

* a matrix $P$, 
* a diagonal matrix $D$, and
* the inverse of $P$ 

... where $P$ holds the eigenvectors of $A$, and $D$ holds the eigenvalues of $A$.

<br>

This is the __eigendecomposition__ of $A$. It is quite fundamental!
::: -->


## How to Diagonalize

:::{style="font-size: .8em"}
Let's put this all together and show a four-step procedure to diagonalize a matrix: 

1. find eigenvalues, 
2. find eigenvectors, 
3. construct $P$, and 
4. construct $D$.

__Example.__  If possible, diagonalize
$A = \begin{bmatrix}1&3&3\\-3&-5&-3\\3&3&1\end{bmatrix}.$
:::

## Step 1
:::{style="font-size: .8em"}
In this case, the characteristic equation turns out to involve a cubic polynomial that can be factored:

$$
\begin{align*}
0 &= \det(A-\lambda I) \\
&= \det\left( \begin{bmatrix}1 - \lambda &3&3\\-3&-5 - \lambda &-3\\3&3&1 - \lambda\end{bmatrix} \right) \\
&= -\lambda^3 - 3\lambda^2 + 4 \\
&= -(\lambda -1)(\lambda +2)^2.
\end{align*}
$$

So the eigenvalues are $\lambda = 1$ and $\lambda = -2$ (with algebraic multiplicity two).
:::

## Step 2
:::{style="font-size: .8em"}

_This is the step where we find out whether or not $A$ can be diagonalized._ The answer depends on whether we can form $n$ linearly independent eigenvectors.

<br>

In this example, we need _three_ linearly independent vectors because $A$ is a $3\times3$ matrix.

For $\lambda = 1$:

Using Gauss-Jordan elimination, we find a nonzero solution to the homogeneous equation $(A - I) {\bf v} = 0$, namely $\mathbf{v}_1 = \begin{bmatrix}1\\-1\\1\end{bmatrix}.$
:::

## Step 2
:::{style="font-size: .8em"}

For $\lambda = -2$: 

We find

$$
\mathbf{v}_2 = \begin{bmatrix}-1\\1\\0\end{bmatrix} \;\text{ and }\; \mathbf{v}_3 = \begin{bmatrix}-1\\0\\1\end{bmatrix}.
$$
Vectors $\mathbf{v}_1$ and $\mathbf{v}_2$ form a basis for the eigenspace $\lambda = -2.$

<br>

It can be shown that $\{\mathbf{v}_1, \mathbf{v}_2, \mathbf{v}_3\}$ forms a linearly independent set.


:::

## Step 3
:::{style="font-size: .8em"}
Next, we construct matrix $P$.

<br>

The order of the vectors is actually not important (yet).

<br>

$$
P = [\mathbf{v}_1\;\mathbf{v}_2\;\mathbf{v}_3] = \begin{bmatrix}1&-1&-1\\-1&1&0\\1&0&1\end{bmatrix}.
$$
:::

## Step 4
:::{style="font-size: .8em"}

It remains to construct matrix $D$. The order of eigenvalues must match the order of eigenvectors used in the previous step.

If an eigenvalue has algebraic multiplicity greater than 1, then repeat it the corresponding number of times.
:::

:::{style="font-size: .6em"}
$$
D = \begin{bmatrix}1&0&0\\0&-2&0\\0&0&-2\end{bmatrix}.
$$
:::
:::{style="font-size: .8em"}
We have diagonalized $A$:
:::
:::{style="font-size: .6em"}
$$
A =  \begin{bmatrix}1&3&3\\-3&-5&-3\\3&3&1\end{bmatrix} =
\underbrace{\begin{bmatrix}1&-1&-1\\-1&1&0\\1&0&1\end{bmatrix}}_{P} \:
\underbrace{\begin{bmatrix}1&0&0\\0&-2&0\\0&0&-2\end{bmatrix}}_{D} \:
\underbrace{\begin{bmatrix}1&-1&-1\\-1&1&0\\1&0&1\end{bmatrix}^{-1}}_{P^{-1}}
$$
:::

## Check
:::{style="font-size: .8em"}

```{python}
#| echo: true
P = np.array([[ 1, -1, -1],
              [-1,  1,  0],
              [ 1,  0,  1]])
D = np.array([[ 1,  0,  0],
              [ 0, -2,  0],
              [ 0,  0, -2]])
print(P @ D @ np.linalg.inv(P))
```

We can now take powers of $A$ quite efficiently:

$$
A^{100} = \begin{bmatrix}1&-1&-1\\-1&1&0\\1&0&1\end{bmatrix}  \begin{bmatrix}1^{100}&0&0\\0&(-2)^{100}&0\\0&0&(-2)^{100}\end{bmatrix}\begin{bmatrix}1&-1&-1\\-1&1&0\\1&0&1\end{bmatrix}^{-1}.
$$
:::

## When Diagonalization Fails

:::{style="font-size: .8em"}

Let's look at another example, this time for a matrix that turns out not to be diagonalizable.

__Example.__ If possible, diagonalize $A = \begin{bmatrix}2&4&3\\-4&-6&-3\\3&3&1\end{bmatrix}.$

__Step 1__: The characteristic equation of $A$ turns out to be the same as in the last example:
$$
0 = \det(A-\lambda I) = -(\lambda-1)(\lambda +2)^2.
$$

Hence, $\lambda_1 = 1$ with algebraic multiplicity one, and $\lambda = -2$ with algebraic multiplicity two.
:::

## When Diagonalization Fails

:::{style="font-size: .8em"}
__Step 2__: we calculate the eigenvectors of $A$ by finding the nullspace of $A - \lambda I$ for both eigenvalues.

It turns out that each eigenspace is only one-dimensional.

Basis for $\lambda_1 = 1$: $\mathbf{v}_1 = \begin{bmatrix}1\\-1\\1\end{bmatrix}.$ Hence, the geometric multiplicity of $\lambda_1$ is 1.

Basis for $\lambda_2 = -2$: $\mathbf{v}_2 = \begin{bmatrix}-1\\1\\0\end{bmatrix}.$ Hence, the geometric multiplicity of $\lambda_2$ is 1 as well.
:::

## When Diagonalization Fails

:::{style="font-size: .8em"}

Every eigenvector of $A$ is a multiple of either $\mathbf{v}_1$ or $\mathbf{v}_2.$  

<br>

Hence, it is impossible to construct $n = 3$ linearly independent eigenvectors of $A$. 

We conclude that $A$ is __not__ diagonalizable.

Let us connect what we just saw to algebraic and geometric multiplicities.
:::

## Criterion for Diagonalization
:::{style="font-size: .8em"}

In general, to be diagonalizable, the algebraic multiplicity of each eigenvalue has to be equal to its geometric multiplicity.

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        The geometric multiplicity of an eigenvalue of a matrix \(A\) is less than or equal to its algebraic multiplicity.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```
<br> 

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        An \(n \times n\) matrix \(A\) is diagonalizable if and only if the algebraic multiplicity of each eigenvalue of  \(A\) is equal to its geometric multiplicity.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

:::

## A Special Case

:::{style="font-size: .8em"}


```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        An \(n\times n\) matrix with \(n\) distinct eigenvalues has \(n\) linearly independent eigenvectors, and therefore is diagonalizable.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

__Example.__ Determine if the following matrix is diagonalizable.

$$
A = \begin{bmatrix}5&-8&1\\0&0&7\\0&0&-2\end{bmatrix}.
$$

- Since $A$ is (upper) triangular, its eigenvalues are $5, 0,$ and $-2$.
- Since $A$ is a $3\times3$ with 3 distinct eigenvalues, $A$ is diagonalizable.
:::

## Geometric Interpretation

:::{style="font-size: .8em"}
Diagonalizing a matrix allows us to bring intuition to its behavior as a linear transformation.

<br>

Diagonalization has a specific interpretation: it separates the influence of each vector component from the others.

<br>
To see what this means, let's first consider a diagonal matrix. When we multiply a vector $\mathbf{x}$ by a diagonal matrix $D$, the change to each component of $\mathbf{x}$ depends only on the component itself. That is, multiplying by a diagonal matrix simply _scales_ the components of the vector.

Let $D = \begin{bmatrix}5&0\\0&3\end{bmatrix}.$ Then, $D \begin{bmatrix}x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix}5x_1 \\ 3x_2 \end{bmatrix}.$
:::

<!-- ## Geometric Interpretation

:::{style="font-size: .8em"}

On the other hand, when we multiply by a matrix $A$ that has off-diagonal entries, the components of $\mathbf{x}$ affect each other.

::: -->

## Geometric Interpretation


:::{style="font-size: .8em"}
In its turn, the multiplication by $P$ can be seen as a change of basis.

Because $P$ is square and invertible, its columns form a basis for $\mathbb{R}^n$.  Let's call that basis $\mathcal{B} = \{\mathbf{p}_1, \mathbf{p}_2, \dots, \mathbf{p}_n\}.$  

Recall that if we have a vector ${\bf y}$ in the standard basis and we want to find its coordinates in the basis $\mathcal{B}$, then we need to solve

$$\mathbf{y} = P\mathbf{x} = x_1 {\bf p}_1 + x_2 {\bf p}_2 + \cdots + x_n {\bf p}_n$$

to find a vector ${\bf x}$ such that ${\bf x} = [{\bf y}]_{\mathcal{B}}$.

Since $P$ is invertible, we can use its inverse to find that ${\bf x} = P^{-1} {\bf y}$.

Similarly, if we start with a vector ${\bf x}$ in the $\mathcal{B}$-basis and want to calculate its coordinates in the standard basis, we can compute ${\bf y} = P {\bf x}$.

:::

## Geometric Interpretation
:::{style="font-size: .8em"}

We can interpret $A {\bf x} = PDP^{-1}\mathbf{x}$ as the following three step geometric transformation:

_Step 1._ Compute the coordinates of $\mathbf{x}$ in the basis $\mathcal{B}$.   

This is $P^{-1}\mathbf{x}.$

<br>

_Step 2._ Scale those coordinates according to the diagonal matrix $D$.   
This is $DP^{-1}\mathbf{x}.$ 

<br>

_Step 3._ Find the point in the standad basis that has those scaled coordinates in the basis $\mathcal{B}.$ 

This is $PDP^{-1}\mathbf{x}.$

:::

<!-- ## Geometric Interpretation
:::{style="font-size: .8em"}

```{python}
#| echo: true
A = np.array([[ 1.86363636, 0.68181819],
              [-0.22727273, 3.13636364]])

P = np.array([[0.98058068, 0.51449576],
              [0.19611614, 0.85749293]])
D = np.array([[2, 0],
              [0, 3]])

np.allclose(A, P @ D @ np.linalg.inv(P))
```
::: -->

## Geometric Interpretation
:::{style="font-size: .8em"}
Consider a fixed-but-unwritten $2 \times 2$ diagonalizable matrix $A$. Below it transforms a point $\mathbf{x} = \begin{bmatrix}2.47\\1.25\end{bmatrix}$.

```{python}
import laUtilities as ut

ax = ut.plotSetup(-1,6,-1,6,size=(12,3.8))
ut.centerAxes(ax)
v1 = np.array([5.0,1.0])
v1 = v1 / np.sqrt(np.sum(v1*v1))
v2 = np.array([3.0,5.0])
v2 = v2 / np.sqrt(np.sum(v2*v2))
p1 = 2*v1+v2
p2 = 4*v1+3*v2
ut.plotVec(ax, p1,'k')
ut.plotVec(ax, p2,'k')
ax.annotate('', xy=(p2[0], p2[1]),  xycoords='data',
                xytext=(p1[0], p1[1]), textcoords='data',
                size=15,
                arrowprops={'arrowstyle': 'simple',
                                'fc': '0.7', 
                                'ec': 'none',
                                'connectionstyle' : 'arc3,rad=-0.3'},
                )
ax.text(2.5,0.75,r'${\bf x}$',size=20)
ax.text(5.2,2.75,r'$A{\bf x}$',size=20)
ax.plot(0,0,'');
```

So far, we cannot say much about what the linear transformation $A$ does in general.
:::

## Geometric Interpretation
:::{style="font-size: .8em"}

Remember that the columns of $P$ are the eigenvectors of $A$.

So $P^{-1}\mathbf{x}$ is the coordinates of the point $\mathbf{x}$ in the __eigenvector basis__, the basis created by the eigenvectors of $A$:

```{python}
#
ax = ut.plotSetup(-1,6,-1,6,size=(12,3.8))
ut.centerAxes(ax)
v1 = np.array([5.0,1.0])
v1 = v1 / np.sqrt(np.sum(v1*v1))
v2 = np.array([3.0,5.0])
v2 = v2 / np.sqrt(np.sum(v2*v2))
ut.plotVec(ax,v1,'b')
ut.plotVec(ax,v2)
ut.plotLinEqn(-v1[1],v1[0],0,color='b')
ut.plotLinEqn(-v2[1],v2[0],0,color='r')
for i in range(-4,8):
    ut.plotLinEqn(-v1[1],v1[0],i*(v1[0]*v2[1]-v1[1]*v2[0]),format=':',color='b')
    ut.plotLinEqn(-v2[1],v2[0],i*(v2[0]*v1[1]-v2[1]*v1[0]),format=':',color='r')
p1 = 2*v1+v2
p2 = 4*v1+3*v2
ut.plotVec(ax, p1,'k')
ax.text(2.5,0.75,r'${\bf x}$',size=20)
ax.text(v2[0]-0.15,v2[1]+0.5,r'${\bf p_2}$',size=20)
ax.text(v1[0]-0.15,v1[1]+0.35,r'${\bf p_1}$',size=20)
ax.plot(0,0,'');
```

The coordinates of $\mathbf{x}$ in this basis are (2,1). In other words $P^{-1}\mathbf{x} = \begin{bmatrix}2\\1\end{bmatrix}.$
:::

## Geometric Interpretation
:::{style="font-size: .8em"}

Next, we compute $DP^{-1}\mathbf{x}.$  Since $D$ is diagonal, this is just scaling each of the $\mathcal{B}$-coordinates.  In this example the eigenvalue corresponding to $\mathbf{p}_1$ is 2, and the eigenvalue corresponding to $\mathbf{p}_2$ is 3.

```{python}
#
ax = ut.plotSetup(-1,6,-1,6,size=(12,3.8))
ut.centerAxes(ax)
v1 = np.array([5.0,1.0])
v1 = v1 / np.sqrt(np.sum(v1*v1))
v2 = np.array([3.0,5.0])
v2 = v2 / np.sqrt(np.sum(v2*v2))
#ut.plotVec(ax,v1,'b')
#ut.plotVec(ax,v2)
ut.plotLinEqn(-v1[1],v1[0],0,color='b')
ut.plotLinEqn(-v2[1],v2[0],0,color='r')
for i in range(-4,8):
    ut.plotLinEqn(-v1[1],v1[0],i*(v1[0]*v2[1]-v1[1]*v2[0]),format=':',color='b')
    ut.plotLinEqn(-v2[1],v2[0],i*(v2[0]*v1[1]-v2[1]*v1[0]),format=':',color='r')
p1 = 2*v1+v2
p2 = 4*v1+3*v2
ut.plotVec(ax, p1,'k')
ut.plotVec(ax, p2,'k')
ax.annotate('', xy=(p2[0], p2[1]),  xycoords='data',
                xytext=(p1[0], p1[1]), textcoords='data',
                size=15,
                #bbox=dict(boxstyle="round", fc="0.8"),
                arrowprops={'arrowstyle': 'simple',
                                'fc': '0.7', 
                                'ec': 'none',
                                'connectionstyle' : 'arc3,rad=-0.3'},
                )
ax.text(2.5,0.75,r'${\bf x}$',size=20)
ax.text(5.2,2.75,r'$A{\bf x}$',size=20)
ax.plot(0,0,'');
```

So the coordinates of $A\mathbf{x}$ in the basis $\mathcal{B}$ are $\begin{bmatrix}2&0\\0&3\end{bmatrix}\begin{bmatrix}2\\1\end{bmatrix} = \begin{bmatrix}4\\3\end{bmatrix}.$
:::

## Geometric Interpretation
:::{style="font-size: .8em"}

Now we convert back to the standard basis. That is, we ask which point has coordinates (4,3) in basis $\mathcal{B}:$
$A\mathbf{x} = P\begin{bmatrix}4\\3\end{bmatrix} = PDP^{-1}\mathbf{x}.$


<!-- We rely on the fact that if $\mathbf{y}$ has coordinates $\mathbf{x}$ in the basis $\mathcal{B}$, then $\mathbf{y} = P\mathbf{x}.$ So  -->



```{python}
#
ax = ut.plotSetup(-1,6,-1,6,size=(12,3.8))
ut.centerAxes(ax)
v1 = np.array([5.0,1.0])
v1 = v1 / np.sqrt(np.sum(v1*v1))
v2 = np.array([3.0,5.0])
v2 = v2 / np.sqrt(np.sum(v2*v2))
#ut.plotVec(ax,v1,'b')
#ut.plotVec(ax,v2)
#ut.plotLinEqn(-v1[1],v1[0],0,color='b')
#ut.plotLinEqn(-v2[1],v2[0],0,color='r')
#for i in range(-3,8):
#    ut.plotLinEqn(-v1[1],v1[0],i*(v1[0]*v2[1]-v1[1]*v2[0]),format=':',color='b')
#    ut.plotLinEqn(-v2[1],v2[0],i*(v2[0]*v1[1]-v2[1]*v1[0]),format=':',color='r')
p1 = 2*v1+v2
p2 = 4*v1+3*v2
#ut.plotVec(ax, p1,'k')
ut.plotVec(ax, p2,'k')
#ax.annotate('', xy=(p2[0], p2[1]),  xycoords='data',
#                xytext=(p1[0], p1[1]), textcoords='data',
#                size=15,
#                #bbox=dict(boxstyle="round", fc="0.8"),
#                arrowprops={'arrowstyle': 'simple',
#                                'fc': '0.7', 
#                                'ec': 'none',
#                                'connectionstyle' : 'arc3,rad=-0.3'},
#                )
#ax.text(2.5,0.75,r'${\bf x}$',size=16)
ax.text(5.2,2.75,r'$A{\bf x}$',size=20)
ax.plot(0,0,'');
```

We find that $A\mathbf{x}$ = $PDP^{-1}\mathbf{x} = \begin{bmatrix}5.46\\3.35\end{bmatrix}.$
:::


## Geometric Interpretation
:::{style="font-size: .8em"}

In conclusion: notice that the transformation $\mathbf{x} \mapsto A\mathbf{x}$ may be a complicated one in which each component of $\mathbf{x}$ affects each component of $A\mathbf{x}$.   

However, by changing to the basis defined by the eigenspaces of $A$, the action of $A$ becomes simple to understand. 

<br>

Diagonalization of $A$ changes the action of $A$ to a basis in which it is easy to understand and compute with.

<br>

Remember that not all matrices are diagonalizable! This particular matrix factorization only applies to square matrices, and not even all square matrices.
:::

## Symmetric Matrices

:::{style="font-size: .8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        A symmetric matrix is a matrix \(A\) such that \(A^\top = A\).
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

Note that if $A$ is an $m \times n$ matrix, then $A^\top$ is an $n \times m$ matrix. For these to be equal, a symmetric matrix _must_ be square.

Here are three _symmetric_ matrices:
:::
:::{style="font-size: .55em"}
$$
\begin{bmatrix}1&0\\0&-3\end{bmatrix},\;\;\;\;\begin{bmatrix}0&-1&0\\-1&5&8\\0&8&-7\end{bmatrix},\;\;\;\;\begin{bmatrix}a&b&c\\b&d&e\\c&e&f\end{bmatrix}.
$$
:::
:::{style="font-size: .8em"}
Here are three _nonsymmetric_ matrices:
:::
:::{style="font-size: .55em"}
$$
\begin{bmatrix}1&-3\\3&0\end{bmatrix},\;\;\;\;\begin{bmatrix}1&3&0\\3&1&0\end{bmatrix},\;\;\;\;\begin{bmatrix}1&-4&0\\-6&1&-4\\0&-6&1\end{bmatrix}.
$$
:::

## Symmetric Matrices

:::{style="font-size: .8em"}
Another example of a symmetric matrix is $A^\top A$ (starting from $A$ of _any_ size).

Given any matrix $A$, the matrix $A^\top A$ is always symmetric because

$$
(A^\top A)^\top = A^\top (A^\top)^\top = (A^\top A).
$$


```{python}
#| echo: true
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A.T @ A)
```

Symmetric matrices have a number of interesting properties. For example, the eigenvectors of a symmetric matrix are _orthogonal_.
:::

<!-- In the remainder of this week, we'll see that symmetric matrices have properties that relate to both eigendecomposition and orthogonality.
::: -->

## Symmetric Matrices

:::{style="font-size: .8em"}

Diagonalize the following symmetric matrix:

$$
A = \begin{bmatrix}6&-2&-1\\-2&6&-1\\-1&-1&5\end{bmatrix}
$$

The characteristic equation of $A$ is

$$\begin{align*}
0 &= \det(A - \lambda I) \\
&= -\lambda^3 + 17\lambda^2 -90\lambda + 144 \\
&= -(\lambda-8)(\lambda-6)(\lambda-3)
\end{align*}
$$

So the eigenvalues are 8, 6, and 3.
:::

## Symmetric Matrices

:::{style="font-size: .8em"}
We construct a basis for each eigenspace by finding the nullspace of $A-\lambda I$:

$$
\lambda_1 = 8: \mathbf{v}_1 = \begin{bmatrix}-1\\1\\0\end{bmatrix};\;\;\;\;\lambda_2=6: \mathbf{v}_2 = \begin{bmatrix}-1\\-1\\2\end{bmatrix};\;\;\;\;\;\lambda_3=3: \mathbf{v}_3=\begin{bmatrix}1\\1\\1\end{bmatrix}.
$$

These three vectors form a basis for $\mathbb{R}^3.$

They also form an _orthogonal set._ That is, any two eigenvectors are orthogonal. 

$$\begin{align*}
\mathbf{v}_1^\top \mathbf{v}_2 &= (-1)(-1) + (1)(-1) + (0)(2) = 0 \\
\mathbf{v}_1^\top \mathbf{v}_3 &= (-1)(1) + (1)(1) + (0)(1) = 0 \\
\mathbf{v}_2^\top \mathbf{v}_3 &= (-1)(1) + (-1)(1) + (2)(1) = 0
\end{align*}
$$

Hence, $\{\mathbf{v}_1, \mathbf{v}_2, \mathbf{v}_3\}$ form an __orthogonal basis__ for $\mathbb{R}^3.$
:::

## Symmetric Matrices

:::{style="font-size: .8em"}
Let's normalize these vectors so they each have length 1:
:::
:::{style="font-size: .6em"}
$$
\mathbf{u}_1 = \begin{bmatrix}-1/\sqrt{2}\\1/\sqrt{2}\\0\end{bmatrix};\;\;\;\;\mathbf{u}_2 = \begin{bmatrix}-1/\sqrt{6}\\-1/\sqrt{6}\\2/\sqrt{6}\end{bmatrix};\;\;\;\;\; \mathbf{u}_3=\begin{bmatrix}1/\sqrt{3}\\1/\sqrt{3}\\1/\sqrt{3}\end{bmatrix}
$$
:::
:::{style="font-size: .8em"}
Let's write the diagonalization of $A$ in terms of these eigenvectors and eigenvalues:
:::
:::{style="font-size: .6em"}
$$
P = \begin{bmatrix}-1/\sqrt{2}&-1/\sqrt{6}&1/\sqrt{3}\\1/\sqrt{2}&-1/\sqrt{6}&1/\sqrt{3}\\0&2/\sqrt{6}&1/\sqrt{3}\end{bmatrix},\;\;\;\;D = \begin{bmatrix}8&0&0\\0&6&0\\0&0&3\end{bmatrix}.
$$
:::
:::{style="font-size: .8em"}
Then, $A = PDP^{-1}$ as usual. Since $P$ is square and has orthonormal columns, $P$ is an _orthogonal_ matrix (AKA an _orthonormal_ matrix). That means $P^{-1} = P^\top$ and $A = PDP^\top.$
:::

## Symmetric Matrices

:::{style="font-size: .7em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        If \(A\) is symmetric, then any two eigenvectors of \(A\) from different eigenspaces are orthogonal.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

__Proof.__  Let $\mathbf{v}_1$ and $\mathbf{v}_2$ be eigenvectors that correspond to distinct eigenvalues, say, $\lambda_1$ and $\lambda_2.$  To show that $\mathbf{v}_1^\top \mathbf{v}_2 = 0,$ compute
$$
\begin{align*}
\lambda_1\mathbf{v}_1^\top \mathbf{v}_2 &= (\lambda_1\mathbf{v}_1)^\top \mathbf{v}_2 \\
&=(A\mathbf{v}_1)^\top \mathbf{v}_2 \\
&=(\mathbf{v}_1^\top A^\top )\mathbf{v}_2 \\
&=\mathbf{v}_1^\top (A^\top \mathbf{v}_2) \\
&=\mathbf{v}_1^\top (A\mathbf{v}_2) \quad \gets \text{this is where we use the fact that $A$ is symmetric} \\
&=\mathbf{v}_1^\top (\lambda_2\mathbf{v}_2) \\
&=\lambda_2\mathbf{v}_1^\top \mathbf{v}_2.
\end{align*}
$$
:::

## Symmetric Matrices 

:::{style="font-size: .8em"}

We conclude that $\lambda_1(\mathbf{v}_1^\top \mathbf{v}_2) = \lambda_2(\mathbf{v}_1^\top \mathbf{v}_2).$

But $\lambda_1 \neq \lambda_2,$ so this can only happen if $\mathbf{v}_1^\top \mathbf{v}_2 = 0.$

Therefore, $\mathbf{v}_1$ is orthogonal to $\mathbf{v}_2.$

<br>

The same argument applies to any other pair of eigenvectors with distinct eigenvalues.

<br>

 That means that any two eigenvectors of $A$ from different eigenspaces are orthogonal.
:::

## Orthogonal Diagonalization

:::{style="font-size: .8em"}
We can now introduce a special kind of diagonalizability.

<br>

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        An \(n\times n\) matrix is said to be <b>orthogonally diagonalizable</b> if there exist an orthogonal matrix \(P\) and a diagonal matrix \(D\) such that 

        \(A = PDP^\top = PDP^{-1}.\)
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

<br>

Such a diagonalization requires $n$ linearly independent and _orthonormal_ eigenvectors.

:::

## The Spectral Theorem

:::{style="font-size: .8em"}
If $A$ is orthogonally diagonalizable, then

$$
A^\top  = (PDP^\top )^\top  = (P^\top )^\top D^\top P^\top  = PDP^\top  = A.
$$

So $A$ is symmetric!

<br>

It turns out the converse is true.

Hence we obtain the following theorem:

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        An \(n\times n\) matrix is orthogonally diagonalizable if and only if it is a symmetric matrix.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```
:::

## The Spectral Theorem

:::{style="font-size: .8em"}
Let us find an orthogonal diagonalization of the matrix
$$A = \begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix}.$$

The eigenvalues of $A$ are the roots of the characteristic equation 
$$\det \left( \begin{bmatrix} 1- \lambda & 2 \\ 2 & 4 - \lambda \end{bmatrix} \right) = \lambda^2 - 5\lambda = \lambda(\lambda-5) = 0.$$

They are $\lambda_1 = 0$ and $\lambda_2 = 5.$ We proceed to find the corresponding eigenvectors. 
:::

## The Spectral Theorem
:::{style="font-size: .8em"}

For $\lambda_1 = 0,$ we have 

$$A - \lambda I = A =\begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix} \sim \begin{bmatrix} 1 & 2 \\ 0 & 0 \end{bmatrix},$$

which yields the eigenspace spanned by $\begin{bmatrix} -2 \\ 1 \end{bmatrix}.$

For $\lambda_2 = 5,$ we have 

$$A - \lambda I = A - 5I  =\begin{bmatrix} -4 & 2 \\ 2 & -1 \end{bmatrix} \sim \begin{bmatrix} 2 & -1 \\ 0 & 0 \end{bmatrix},$$

which yields the eigenspace spanned by $\begin{bmatrix} 1 \\ 2 \end{bmatrix}.$
:::

## The Spectral Theorem
:::{style="font-size: .8em"}
It remains to contruct $P$ and $D$: 
$$P = \begin{bmatrix} -2/\sqrt{5} & 1/\sqrt{5} \\ 1/\sqrt{5} & 2/\sqrt{5} \end{bmatrix} \text { and } D = \begin{bmatrix} 0 & 0 \\ 0 & 5\end{bmatrix}.$$

Hence, the orthogonal diagonalization of $A$ is 
$$A = PDP^\top = \begin{bmatrix} -2/\sqrt{5} & 1/\sqrt{5} \\ 1/\sqrt{5} & 2/\sqrt{5} \end{bmatrix} \begin{bmatrix} 0 & 0 \\ 0 & 5\end{bmatrix} \begin{bmatrix} -2/\sqrt{5} & 1/\sqrt{5} \\ 1/\sqrt{5} & 2/\sqrt{5} \end{bmatrix}.$$

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        Find an orthogonal diagonalization of \( \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}.\)
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```
:::

## The Spectral Theorem
:::{style="font-size: .8em"}
Find an orthogonal diagonalization of the matrix $A = \begin{bmatrix}
1 & -1 & -1 \\
-1 & 1 & -1 \\
-1 & -1 & 1
\end{bmatrix}.$

It can be shown that the eigenvalues of $A$ are $\lambda_1 = -1$, with algebraic multiplicity 1, and $\lambda_2 = 2$ with algebraic multiplicity 2.

The eigenspace of $\lambda_1$ is spanned by $\mathbf{v}_1 = \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}$.

The eigenspace of $\lambda_2$ is spanned by $\mathbf{v}_2 = \begin{bmatrix} -1 \\ 1 \\ 0 \end{bmatrix}$ and $\mathbf{v}_3 = \begin{bmatrix} -1 \\ 0 \\ 1 \end{bmatrix}.$


<!-- $$\lambda_1 = -1, \operatorname{span} \left\{ \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix} \right\},$$
$$\lambda_2 = \lamba_3, \operatorname{span} \left\{ \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix} \right\},$$ -->
:::

## The Spectral Theorem
:::{style="font-size: .8em"}
Notice that $\mathbf{v}_2$ and $\mathbf{v}_3$ are orthogonal to $\mathbf{v}_1$, as must be the case for this $A$ is symmetric. 

<br>

On the other hand, $\mathbf{v}_2$ and $\mathbf{v}_3$ are not orthogonal. In fact, $\mathbf{v}_2^\top \mathbf{v}_3 = 1.$ 
This is because they both belong to the eigenspace of $\lambda_2.$

<br>

Since we interested in an orthogonal diagonalization of $A$ and $\mathbf{v}_2$ and $\mathbf{v}_3$ are linearly independent, we can use the Gram-Schmidt process to orthogonalize these vectors.

:::

## The Spectral Theorem
:::{style="font-size: .8em"}


We replace $\mathbf{v}_3$ by 

$$\mathbf{u}_3 = \mathbf{v}_3 - \frac{\mathbf{v}_3^\top \mathbf{v}_2}{\mathbf{v}_2^\top \mathbf{v}_2} \mathbf{v}_2 = \begin{bmatrix} -1 \\ 0 \\ 1 \end{bmatrix} - \frac{1}{2}\begin{bmatrix} -1 \\ 1 \\ 0 \end{bmatrix} = \begin{bmatrix} -1/2 \\ -1/2 \\ 1 \end{bmatrix}.$$

The set $\{\mathbf{v}_1, \mathbf{v}_2, \mathbf{u}_3\}$ is orthogonal. We obtain $P$ by normalizing each of the vectors in this set:
$$P = \begin{bmatrix} 1/\sqrt{3} & -1/\sqrt{2} & -1/\sqrt{6}\\
1/\sqrt{3} & 1/\sqrt{2} & -1/\sqrt{6}\\ 1/\sqrt{3} & 0 & 2/\sqrt{6} \end{bmatrix}.$$

<!-- The matrix $D$ is equal to $\begin{bmatrix} -1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 2\end{bmatrix}.$ -->

:::

## The Spectral Theorem
:::{style="font-size: .8em"}

The matrix $D$ is equal to $\begin{bmatrix} -1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 2\end{bmatrix}.$

Hence, 
:::
:::{style="font-size: .6em"}
$$A = \begin{bmatrix} 1/\sqrt{3} & -1/\sqrt{2} & -1/\sqrt{6}\\
1/\sqrt{3} & 1/\sqrt{2} & -1/\sqrt{6}\\ 1/\sqrt{3} & 0 & 2/\sqrt{6}  \end{bmatrix} \begin{bmatrix} -1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 2\end{bmatrix} \begin{bmatrix} 1/\sqrt{3} & -1/\sqrt{2} & -1/\sqrt{6}\\
1/\sqrt{3} & 1/\sqrt{2} & -1/\sqrt{6}\\ 1/\sqrt{3} & 0 & 2/\sqrt{6} \end{bmatrix}^T.$$

:::

## Key Ideas

:::{style="font-size: .8em"}
- We say that a square matrix $A$ is diagonalizable, if it is similar to a diagonal matrix: $A = PDP^{-1}$.
- An $n \times n$ matrix  $A$ is diagonalizable if and only if it has $n$ linearly independent eigenvectors. This is the case when the algebraic multiplicity of each eigenvalue of  $A$ is equal to its geometric multiplicity.
- If $A$ is symmetric, then it is orthogonally diagonalizable: $A = PDP^\top.$ The eigenvectors corresponding to distinct eigenvalues are always orthogonal. The eigenvalues corresponding to the same eigenvalue can be orthogonalize using the Gram-Schmidt process.

:::
