---
title: Properties of Eigenvalues 
author: "CDS DS-121<br>Boston University"
format: 
    revealjs:
        math: true
        css: 
        - styles.css
        html-math-method: mathjax
        highlight-style: github
---

## Learning Objectives
:::{style="font-size: .8em"}
Today we will continue our discussion about eigenvalues and eigenvectors. We will cover:

*  Eigenvalues of triangular matrices
*  Algebraic and geometric multiplicities of eigenvalues
*  The connection between eigenvalues and matrix singularity
*  The connection between eigenvalues and matrix similarity
*  Important warnings about eigenvalues 

Finally, we will connect eigenvalues and eigenvectors to our Markov chain example on population distribution.
:::


## Eigenvalues of a Triangular Matrix

:::{style="font-size: .8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        The eigenvalues of a triangular matrix are the entries on its main diagonal.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

__Proof.__ See the notes.

<br>

__Example.__ Let $A = \begin{bmatrix}3&6&-8\\0&0&6\\0&0&2\end{bmatrix}$ and $B = \begin{bmatrix}4&0&0\\-2&1&0\\5&3&4\end{bmatrix}$. 

Then the eigenvalues of $A$ are 3, 0, and 2.   The eigenvalues of $B$ are 4 and 1.
:::

## Multiplicity

:::{style="font-size: .8em"}
Note that one of the eigenvalues of $B$ occurs twice. We say that it is _repeated_. 

<br>

In general, every eigenvalue has a certain __algebraic multiplicity__. Algebraic multiplicity counts the repetitions of $\lambda$ among the eigenvalues.

<br>

The eigenvalue 4 of $B$ has algebraic mulitiplicity of 2, while the eigenvalue 1 has algebraic multiplicity of 1. 

<br>

Next to algebraic multiplicity, there is also the __geometric multiplicity__ of an eigenvalue. The geometric multiplicty counts the independent eigenvectors <br> for $\lambda.$

:::

## Multiplicity

:::{style="font-size: .8em"}

Consider $C = \begin{bmatrix} 0 & 1 \\ 0 & 0 \end{bmatrix}.$ 

* $C$ has one (repeated) eigenvlaue: 0.
* There is only one eigenvector describing the eigenspace of $\lambda =0$: $\begin{bmatrix} 1 \\ 0 \end{bmatrix}.$
* The algebraic multiplicity of $\lambda = 0$ is 2.
* The geometric multiplicity of $\lambda = 0$ is 1.


```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        Let \(A = \begin{bmatrix} 7 & 2 \\ -2 & 3 \end{bmatrix}.\)<br>

        What are the algebraic and geometric multiplicities of its eigenvalues? <br>
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

:::

## Invertibility

:::{style="font-size: .8em"}
What happens if a matrix $A$ has 0 as an eigenvalue?

<br> 

This happens if and only if there is a nontrivial solution to the equation

$$\begin{align*}
A\mathbf{x} &= 0\mathbf{x} \\
A\mathbf{x} &= {\bf 0}.
\end{align*}$$

<br>

By the IMT, the homogeneous equation has a nontrivial solution if and only if $A$ is not invertible. Hence, 0 is an eigenvalue of $A$ if and only if $A$ is not invertible.
:::


## Invertibility

:::{style="font-size: .8em"}
So we have yet another addition to the Invertible Matrix Theorem!

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        Let \(A\) be an \(n\times n\) matrix. Then the following two statements are equivalent:<br>
        <ol start="1">
    <li> \(A\) is invertible. <br>
    <li> The number 0 is not an eigenvalue of \(A\).
    </ol>
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```
<br>

__Example.__ $A = \begin{bmatrix}3&6&-8\\0&0&6\\0&0&2\end{bmatrix}$ with eigenvalues 3, 0, and 2 is not invertible. 
:::

## Similarity

:::{style="font-size: .8em"}

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        If \(A\) and \(B\) are \(n\times n\) matrices, then \(A\) is <b>similar</b> to \(B\) if there is an invertible matrix \(P\) such that \(P^{-1}AP = B,\) or, equivalently, \(A = PBP^{-1}.\)
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```
<br>

 Similarity is a symmetric relationship: if $A$ is similar to $B$, then $B$ is similar to $A$.  Hence we just say that $A$ and $B$ _are similar._
 
<br> 
Changing $A$ into $B$ is called a __similarity transformation.__

:::

## Similarity

:::{style="font-size: .8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        If \(n\times n\) matrices \(A\) and \(B\) are similar, then they have the same characteristic polynomial, and hence the same eigenvalues.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```
__Proof.__  If $B = P^{-1}AP,$ then

$$\begin{align*}
B - \lambda I &= P^{-1}AP - \lambda I \\
&= P^{-1}AP - \lambda P^{-1}P \\
&= P^{-1}(AP-\lambda P) \\
&= P^{-1}(A-\lambda I)P.
\end{align*}$$

:::

## Similarity

:::{style="font-size: .8em"}
Now let's construct the characteristic polynomial by taking the determinant:

$$\begin{align*}
\det(B-\lambda I) &= \det[P^{-1}(A-\lambda I)P] \\
&= \det(P^{-1})\cdot\det(A-\lambda I)\cdot\det(P),
\end{align*}
$$

using the fact that the determinant of the product of matrices equals the product of the determinants.

<br>

Finally, since $\det(P^{-1})\cdot\det(P) = \det(P^{-1}P) = \det I = 1,$ we can see that 

$$\det(B-\lambda I) = \det(A - \lambda I).$$
:::

## Warnings

:::{style="font-size: .8em"}
1. The eigenvalues of a matrix with real entries might be complex.

__Example.__ Consider the "rotation by 90 degrees" matrix:

$$A = \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}.$$

It does not have any real-valued eigenvalues.

```{python}
import numpy as np
import laUtilities as ut
```

```{python}
#| echo: true
A = np.array([[0, -1],
              [1,  0]])
for i in range(len(A)):
    print("eigenvalue", np.round(np.linalg.eigvals(A)[i]), "with eigenvector", np.round(np.linalg.eig(A)[1][:,i], 5))
```
:::

## Warnings

:::{style="font-size: .8em"}
2. Elimination does not preserve eigenvalues.

If you add a row of a matrix to its other row, or exchange its rows, the eigenvalues usually change.

__Example.__  Consider $A = \begin{bmatrix} 1 & 3 \\ 2 & 6 \end{bmatrix}$.

* Its characteristic equation is $(1-\lambda)(6-\lambda) - 6 = \lambda^2 - 7 \lambda = \lambda (\lambda - 7) = 0.$
Hence, its eigenvalues are 0 and 7.
* The reduced echelon form of $A$ is $U = \begin{bmatrix} 1 & 3 \\ 0 & 0 \end{bmatrix}.$ The eigenvalues of $U$ are 0 and 1.

:::

## Back to Markov Chains

:::{style="font-size: .8em"}
Recall that a _Markov chain_ models systems that change over time. It imposes a fixed rule that tells us how to compute the next state of the system based on the current state of the system (no matter the prior history or which time period we're currently at).

Formally, a Markov chain is represented by:

- An initial probability vector $\mathbf{x_0} \in \mathbb{R}^n$ showing the fraction of people/objects in each state at the beginning of the system, and
- A stochastic matrix $P \in \mathbb{R}^{n \times n}$ that encodes the state transition rule, in the sense that the next state is calculated as ${\bf x_{k+1}} = P{\bf x_k}$.
:::

## Back to Markov Chains

:::{style="font-size: .8em"}
In the long run, it can be shown that every stochastic matrix has at least one __steady-state vector__ ${\bf v}$ such that $P{\bf v} = {\bf v}$.

To find the steady-state vector for a Markov Chain:

* Solve the linear system $(P-I){\bf x} = {\bf 0}.$  
* The system will have an infinite number of solutions, with one free variable.  Obtain a general solution.
* Pick any specific solution (choose any value for the free variable), and scale it so the entries add up to 1.
:::

## Eigenvalues of Markov Chains
:::{style="font-size: .8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        The largest eigenvalue of a Markov Chain is 1.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```
__Proof.__ See the notes.

<br> 

_How long does it take_ for a particular Markov Chain to reach steady state from some initial starting condition?

The answer to this question turns out to be related to the _second largest_ eigenvalue.

:::


## Eigenvalues of Markov Chains

:::{style="font-size: .8em"}
__Example.__ Let's use our running example of population movement between the city and the suburbs, defined by the stochastic matrix

$$A = \begin{bmatrix}0.95&0.03\\0.05&0.97\end{bmatrix}.$$

We previously saw that $A$ is a regular matrix and the unique steady-state vector is $\begin{bmatrix}3/8 \\ 5/8 \end{bmatrix}$.

Today, let's ask _how long_ until it reaches steady state, from the starting point defined as $\mathbf{x}_0 = \begin{bmatrix}0.6\\0.4\end{bmatrix}.$

:::

## Eigenvalues of Markov Chains

:::{style="font-size: .8em"}

The matrix $A$ has the characteristic equation:
    
$$\lambda^2 -1.92\lambda +0.92 = 0. $$

The corresponding eigenvalues are 1 and 0.92.

We can find a basis for each eigenspace of $A$ (each nullspace of $A-\lambda I$).  

- For $\lambda_1 = 1$, a corresponding eigenvector is $\mathbf{v}_1 = \begin{bmatrix}3/8 \\5/8 \end{bmatrix}.$ This is a steady state vector we found earlier! 
- For $\lambda_2 = 0.92$, a corresponding eigenvector is $\mathbf{v}_2 = \begin{bmatrix}1\\-1\end{bmatrix}.$
:::

## Eigenvalues of Markov Chains

:::{style="font-size: .8em"}
Note: $\{\mathbf{v}_1,\mathbf{v}_2\}$ is a linearly independent set of two vectors in $\mathbb{R}^2$, so it is a basis for $\mathbb{R}^2.$

Therefore, the initial state $\mathbf{x}_0 = \begin{bmatrix}0.6\\0.4\end{bmatrix}$ can be written as a linear combination of $\mathbf{v}_1$ and $\mathbf{v}_2:$ 

$$\mathbf{x}_0 = c_1\mathbf{v}_1 + c_2\mathbf{v}_2.$$

Other state vectors $\mathbf{x}_k$ can be written as a linear combination of the eigenvectors as well.
:::

## Eigenvalues of Markov Chains

:::{style="font-size: .8em"}
$$\begin{eqnarray*}
\mathbf{x}_1 &=& A\mathbf{x}_0 \\
&=& A(c_1\mathbf{v}_1 + c_2\mathbf{v}_2)\\
&=& c_1A\mathbf{v}_1 + c_2A\mathbf{v}_2\\
&=& c_1\lambda_1\mathbf{v}_1 + c_2 \lambda_2 \mathbf{v}_2 \\
&=& c_1\mathbf{v}_1 + c_2 \lambda_2 \mathbf{v}_2.
\end{eqnarray*}
$$

Similarly, we find
$$\begin{eqnarray*}
\mathbf{x}_2 &=& A\mathbf{x}_1 \\
&=& c_1\mathbf{v}_1 + c_2({\lambda_2})^2\mathbf{v}_2.
\end{eqnarray*}
$$

In general:
$$\mathbf{x}_k = c_1\mathbf{v}_1 + c_2(\lambda_2)^k\mathbf{v}_2\;\;\;(k = 0, 1, 2, \dots).$$
:::


## Eigenvalues of Markov Chains

:::{style="font-size: .8em"}
For the specific $c_1,c_2,\mathbf{v}_1,\mathbf{v}_2$ and $\lambda_2$ in the city-suburbs example:

$$\mathbf{x}_k = \begin{bmatrix}3/8 \\ 5/8 \end{bmatrix} + 0.225(0.92)^k\begin{bmatrix}1\\-1\end{bmatrix}\;(k = 0, 1, 2, \dots)$$

In other words:
:::
:::{style="font-size: .6em"}
$$\begin{eqnarray}
\mathbf{x}_0 &= \begin{bmatrix}3/8 \\ 5/8 \end{bmatrix} + 0.225\begin{bmatrix}1\\-1\end{bmatrix}\\
\mathbf{x}_1 &= \begin{bmatrix}3/8 \\ 5/8 \end{bmatrix} + 0.207\begin{bmatrix}1\\-1\end{bmatrix}\\ 
\mathbf{x}_2 & = \begin{bmatrix}3/8 \\ 5/8 \end{bmatrix} + 0.190\begin{bmatrix}1\\-1\end{bmatrix}\\
& \vdots \\
\mathbf{x}_\infty & = \begin{bmatrix}3/8 \\ 5/8 \end{bmatrix}
\end{eqnarray}$$   
:::

## Eigenvalues of Markov Chains

:::{style="font-size: .8em"}
:::{.center-text}
```{python}
#| echo: false
#
ax = ut.plotSetup(-0.1,1.7,-0.1,1.2)
ut.centerAxes(ax)
A = np.array([[0.95,0.03],[0.05,0.97]])
v1 = np.array([0.375,0.625])
v2 = np.array([0.225,-0.225])
x0 = v1 + v2
#
ax.plot([1,0],[0,1],'b--')
ax.text(v1[0]+0.02,v1[1]+0.02,r'${\bf v_1}$',size=16)
ax.plot(x0[0],x0[1],'bo')
v = np.zeros((40,2))
for i in range(40):
    v[i] = v1+(0.92**i)*v2
    ax.plot(v[i,0],v[i,1],'o')
ax.text(v[4][0]+0.02,v[4][1]+0.02,r'${\bf x_4}$',size=12)
ax.text(v[10][0]+0.02,v[10][1]+0.02,r'${\bf x_{10}}$',size=12)
ax.text(x0[0]+0.02,x0[1]+0.02,r'${\bf x_0}$',size=16)
ax.plot(v1[0],v1[1],'ro')
#ax.text(A.dot(x0)[0]+0.2,A.dot(x0)[1]+0.2,r'$A{\bf x_0}$',size=16)
# ax.plot([-10,10],[5*10/6.0,-5*10/6.0],'b-')
#
ax.annotate('Steady State', xy=(v1[0], v1[1]),  xycoords='data',
                xytext=(0.1, 0.2), textcoords='data',
                size=15,
                #bbox=dict(boxstyle="round", fc="0.8"),
                arrowprops={'arrowstyle': 'simple',
                                'fc': '0.5', 
                                'ec': 'none',
                                'connectionstyle' : 'arc3,rad=-0.3'},
                )
ax.annotate('Initial State', xy=(v[0,0], v[0,1]),  xycoords='data',
                xytext=(0.4, 0.8), textcoords='data',
                size=15,
                #bbox=dict(boxstyle="round", fc="0.8"),
                arrowprops={'arrowstyle': 'simple',
                                'fc': '0.5', 
                                'ec': 'none',
                                'connectionstyle' : 'arc3,rad=-0.3'},
                )
print('')
```
:::
- If $\lambda_2$ is small (i.e., its absolute value is close to 0), then $\lambda_2^k$ decays to 0 rapidly, so the Markov chain quickly approaches the steady-state vector.
- If $\lambda_2$ is large, then $\lambda_2^k$ decays to 0 gradually, so the Markov chain slowly (but eventually) approaches the steady-state vector.
:::

## Key Ideas

:::{style="font-size: .8em"}

* The eigenvalues of a triangular matrix are the entries on its main diagonal.
* Algebraic multiplicity counts the repetitions of an eigenvalue. Geometric multiplicity counts the corresponding independent eigenvectors.
* If a matrix has a 0 eigenvalue, it is not invertible.
:::