---
title: "Least Squares"
author: "CDS DS-121<br>Boston University"
format: 
    revealjs:
        math: true
        css: 
        - styles.css
        html-math-method: mathjax
        highlight-style: github
---

## Learning Objectives

:::{style="font-size: .8em"}
Today we will define the least squares solution to an inconsistent system of equations using normal equations. 

We will connect this solution to projections. By understanding the geometric interpretation of least squares, we will see how the solution minimizes the distance between the observed data and the model's predictions. This approach is fundamental to linear regression that will be introduced in the next lecture.
:::

## Solving Linear Systems

:::{style="font-size: .75em"}
<!-- It often happens that $A\mathbf{x} = \mathbf{b}$ has no solutions. The usual reason is: _too many equations_. The matrix $A$ has more rows than columns. If $A$ is $m \times n$, $m>n$. 

Let us consider the example below. -->

In 2014, data was collected regarding the percentage of linear algebra exercises done by students and the grade they received on their examination. Based on this data, we aim to determine the expected effect of completing an additional $10\%$ of the exercises on a student's exam grade.

| ID | % of Exercises | Exam Grade |
|----|----------------|------------|
| 1  | 20             | 55         |
| 2  | 100            | 100        |
| 3  | 90             | 100        |
| 4  | 70             | 70         |
| 5  | 50             | 75         |
| 6  | 10             | 25         |
| 7  | 30             | 60         |

:::

## Solving Linear Systems
:::{style="font-size: .8em"}

We assume a linear relationship between the percentage of exercises completed and the exam grade. We can express this relationship using 
$A\mathbf{x} = \mathbf{b}$ with
:::

:::{style="font-size: .7em"}
$$
     A = \begin{pmatrix}
     1 & 20 \\
     1 & 100 \\
     1 & 90 \\
     1 & 70 \\
     1 & 50 \\
     1 & 10 \\
     1 & 30 \\
     \end{pmatrix} \text{ and }
     b = \begin{pmatrix}
     55 \\
     100 \\
     100 \\
     70 \\
     75 \\
     25 \\
     60 \\
     \end{pmatrix}.
$$
:::

:::{style="font-size: .8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        Will this system have a solution?
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

:::

## Inconsistent Systems

:::{style="font-size: .8em"}
The system from our example has no solutions. It is inconsistent.

</br>

It often happens that $A\mathbf{x} = \mathbf{b}$ has no solutions. The usual reason is: _too many equations_. The matrix $A$ has more rows than columns. If $A$ is $m \times n$, then $m>n$. 

</br>

Unless measuraments are perfect, Gauss-Jordan elimination reaches an impossible point and stops. But we can't stop because our data includes noise (or errors).


:::



## Inconsistent Systems

:::{style="font-size: .8em"}

If $A$ is $m\times n$ and $A\mathbf{x} = \mathbf{b}$ has no solutions, that is because the columns of $A$ do not span $\mathbb{R}^m$ and $\mathbf{b}$ is not in the column space of $A$.

Our assumption is that the reason that $\mathbf{b}$ does not lie in $\operatorname{Col}\,A$ is due to an error in the data.
Here is an example where $A$ is $3 \times 2$:

:::{.center-text}
```{python}
import laUtilities as ut
import matplotlib.pyplot as plt
import numpy as np

qr_setting = None

#
fig = ut.three_d_figure((9, 1), 'b is not in Col A',
                        -15, 15, -15, 15, -15, 15, (5, 5), qr = qr_setting)
a2 = np.array([5.0,-13.0,-3.0])
a1 = np.array([1,-2.0,3])
v = -3*a1 + a2
y = np.array([12.0, 8.0, -5.0])
A = np.array([a1, a2]).T
#
# plotting the span of v
fig.plotSpan(a1, a2, 'Green')
#
#
fig.plotPoint(y[0], y[1], y[2],'b')
fig.text(y[0]+0.5, y[1]+0.5, y[2]+0.5, r'$\bf b$', 'b', size=18)
#
# origin seems unhelpful
#fig.plotPoint(0, 0, 0, 'b')
#fig.text(0-1.5, 0-1.5, 0-1.5, r'$\bf 0$', '0', size=18)
#
#
wpos = -4.5*a1 
fig.text(wpos[0], wpos[1], wpos[2], r'Col $A$', 'Col A', size=22)

#ut.plotPoint3d(ax,0,0,0,'b')
fig.ax.view_init(azim=85,elev=-10)
fig.hideAxes() 
```
:::
:::

## Inconsistent Systems

:::{style="font-size: .8em"}
What can we do when $A\mathbf{x} = \mathbf{b}$ has _no solutions_?

We need an approach to doing the best job we can given the errors in our data.

<br>

If we make the assumption that the errors in the data are small, then we should be quite satisfied to find an $\mathbf{x}$ that makes $A\mathbf{x}$ as close as possible to $\mathbf{b}.$

<br>

In other words, we are looking for an $\mathbf{x}$ such that $A\mathbf{x}$ makes a good __approximation__ to $\mathbf{b}.$
:::

## Inconsistent Systems

:::{style="font-size: .8em"}
:::{.center-text}
```{python}
#
fig = ut.three_d_figure((9, 2), 'b should be close to Ax',
                        -15, 15, -15, 15, -15, 15, (6, 5), qr = qr_setting)
a2 = np.array([5.0,-13.0,-3.0])
a1 = np.array([1,-2.0,3])
v = -3*a1 + a2
y = np.array([12.0, 8.0, -5.0])
A = np.array([a1, a2]).T
#
# plotting the span of v
fig.plotSpan(a1, a2, 'Green')
#
yhat = A @ np.linalg.inv(A.T @ A) @ A.T @ y
fig.plotPoint(yhat[0], yhat[1], yhat[2], 'b')
fig.text(yhat[0]+0.5, yhat[1]+0.5, yhat[2]+0.5, r'$A\mathbf{x}$', 'Ax', size=18)
#
fig.plotPoint(y[0], y[1], y[2],'b')
fig.text(y[0]+0.5, y[1]+0.5, y[2]+0.5, r'$\bf b$', 'b', size=18)
#
# origin seems unhelpful
#fig.plotPoint(0, 0, 0, 'b')
#fig.text(0-1.5, 0-1.5, 0-1.5, r'$\bf 0$', '0', size=18)
#
#
wpos = -4.5*a1 
fig.text(wpos[0], wpos[1], wpos[2], r'Col $A$', 'Col A', size=22)

#ut.plotPoint3d(ax,0,0,0,'b')
fig.ax.view_init(azim=85,elev=-10)
fig.hideAxes() 
```
:::

We can think of the quality of the approximation of $A\mathbf{x}$ to $\mathbf{b}$ as the distance from $A\mathbf{x}$ to $\mathbf{b},$ which is $\Vert A\mathbf{x} - \mathbf{b}\Vert.$
:::

## Least-Squares Problem

:::{style="font-size: .8em"}
The __general least-squares problem__ is to find an $\mathbf{x}$ that makes $\Vert A\mathbf{x}-\mathbf{b}\Vert$ as small as possible.

This is called "least squares" because it is equivalent to minimizing $\Vert A\mathbf{x}-\mathbf{b}\Vert^2,$ which is the sum of squared differences.

<br>

Just to make this explicit: say that we denote $A\mathbf{x}$ by $\mathbf{y}$. Then

$$
\Vert A\mathbf{x}-\mathbf{b}\Vert^2 = \sum_i (y_i-b_i)^2
$$

Where we interpret $y_i$ as the __estimated value__ and $b_i$ as the __measured value__.

<br>

Hence, this expression is the __sum of squared errors.__  
:::

## Least-Squares Problem

:::{style="font-size: .8em"}
Minimizing the length of $A\mathbf{x} - \mathbf{b}$ is the same as minimizing the sum of squared error.
<br>

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        If A is \(m\times n\) and \(\mathbf{b}\) is in \(\mathbb{R}^m,\) a <b>least squares solution</b> of \(A\mathbf{x} =\mathbf{b}\) is an \(\mathbf{\hat{x}}\) in \(\mathbb{R}^n\) such that \(\Vert A\mathbf{\hat{x}} - \mathbf{b}\Vert \leq \Vert A\mathbf{x} - \mathbf{b}\Vert\) for all \(\mathbf{x}\) in \(\mathbb{R}^n\).
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```
<br>

The point here is that no matter what $\mathbf{x}$ is, $A\mathbf{x}$ will be in the column space of $A.$ 

So $\mathbf{b}$ is outside $\operatorname{Col}A$, and we are looking for $\hat{\mathbf{x}}$, which specifies the closest point in $\operatorname{Col}A$ to $\mathbf{b}$.
:::

## Least-Squares Problem

:::{style="font-size: .8em"}
:::{.center-text}
```{python}
#
fig = ut.three_d_figure((9, 3), 'Least Squares looks for the Closest Point in Col A',
                        -15, 15, -15, 15, -15, 15, (5, 4), qr = qr_setting)
a2 = np.array([5.0,-13.0,-3.0])
a1 = np.array([1,-2.0,3])
v = -3*a1 + a2
y = np.array([12.0, 8.0, -5.0])
A = np.array([a1, a2]).T
#
# plotting the span of v
fig.plotSpan(a1, a2, 'Green')
#
yhat = A @ np.linalg.inv(A.T @ A) @ A.T @ y
fig.plotPoint(yhat[0], yhat[1], yhat[2], 'b')
fig.text(yhat[0]+0.5, yhat[1]+0.5, yhat[2]+0.5, r'$\mathbf{A\hat{x}}$', 'Ax-hat', size=18)
#
fig.plotPoint(y[0], y[1], y[2],'b')
fig.text(y[0]+0.5, y[1]+0.5, y[2]+0.5, r'$\bf b$', 'b', size=18)
#
# origin seems unhelpful
#fig.plotPoint(0, 0, 0, 'b')
#fig.text(0-1.5, 0-1.5, 0-1.5, r'$\bf 0$', '0', size=18)
#
x1 = y + np.array([8, 8, 8])
x1hat = A @ np.linalg.inv(A.T @ A) @ A.T @ x1
fig.plotPoint(x1hat[0], x1hat[1], x1hat[2], 'r')
#
x2 = y + np.array([-4, -6, 6])
x2hat = A @ np.linalg.inv(A.T @ A) @ A.T @ x2
fig.plotPoint(x2hat[0], x2hat[1], x2hat[2], 'r')
#
wpos = -4.5*a1 
fig.text(wpos[0], wpos[1], wpos[2], r'Col $A$', 'Col A', size=22)
#
# lines
fig.plotLine([y, yhat], 'b', '-')
fig.plotLine([y, x1hat], 'r', '--')
fig.plotLine([y, x2hat], 'r', '--')

#ut.plotPoint3d(ax,0,0,0,'b')
fig.ax.view_init(azim=100,elev=-20.0)
fig.hideAxes() 
```
:::

The vector $\mathbf{b}$ is closer to $A\mathbf{\hat{x}}$ than it is to $A\mathbf{x}$ for any other $\mathbf{x}$.

For example, the red points in the figure are both _further_ from  $\mathbf{b}$ than is $A\mathbf{\hat{x}}$.

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        How should we find the closest point in \(\operatorname{Col}(A)\) to \(\mathbf{b}\)?
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

<!-- To solve the Least Squares problem, we need to use a concept that we studied last week: orthogonal projection onto a subspace. -->

:::

## Projection Solves Least Squares{.smaller-title}

:::{style="font-size: .9em"}
We want $A\hat{\mathbf{x}}$ to be the closest point in $\operatorname{Col}A$ to $\mathbf{b}$.
<br>

We know that the closest point to $\mathbf{b}$ in a subspace $W$ is the __projection__ of $\mathbf{b}$ onto $W$:

$$
\hat{\mathbf{b}} = \mbox{proj}_{\operatorname{Col}A} \mathbf{b}.
$$
<br>

The key is that $\hat{\mathbf{b}}$ _is_ in the column space of $A$.   So this equation is consistent, and we can solve it:

$$
A\mathbf{\hat{x}} = \hat{\mathbf{b}}.
$$
:::

## Projection Solves Least Squares{.smaller-title}

:::{style="font-size: .8em"}
:::{.center-text}
```{python}
#
fig = ut.three_d_figure((9, 4), 'Least Squares looks for the Closest Point in Col A',
                        -15, 15, -15, 15, -15, 15, (5, 5), qr = qr_setting)
a2 = np.array([5.0,-13.0,-3.0])
a1 = np.array([1,-2.0,3])
v = -3*a1 + a2
y = np.array([12.0, 8.0, -5.0])
A = np.array([a1, a2]).T
#
# plotting the span of v
fig.plotSpan(a1, a2, 'Green')
#
yhat = A @ np.linalg.inv(A.T @ A) @ A.T @ y
fig.plotPoint(yhat[0], yhat[1], yhat[2], 'b')
fig.text(yhat[0]+0.5, yhat[1]+0.5, yhat[2]+0.5, r'$\mathbf{A\hat{x}} = \hat{\mathbf{b}}$', 'Ax-hat', size=18)
#
fig.plotPoint(y[0], y[1], y[2],'b')
fig.text(y[0]+0.5, y[1]+0.5, y[2]+0.5, r'$\bf b$', 'b', size=18)
#
#
wpos = -4.5*a1 
fig.text(wpos[0], wpos[1], wpos[2], r'Col $A$', 'Col A', size=22)
#
# lines
fig.plotLine([y, yhat], 'b', '-')
#
fig.plotPerpSym(yhat, y, a2-5*a1, 2.5)
#

#ut.plotPoint3d(ax,0,0,0,'b')
fig.ax.view_init(azim=100,elev=-20.0)
fig.hideAxes() 
```
:::

Since $\hat{\mathbf{b}}$ is the closest point in $\operatorname{Col}A$ to $\mathbf{b},$ a vector $\hat{\mathbf{x}}$ is a least-squares solution of $A\mathbf{x}=\mathbf{b}$ if and only if $\mathbf{\hat{x}}$ satisfies $A\mathbf{\hat{x}} = \hat{\mathbf{b}}.$ We know that $A\mathbf{\hat{x}} =\hat{\mathbf{b}}$ is consistent.
However, if $A$ has free variables (the columns of $A$ are dependent) there are infinitely many solutions of $A\mathbf{\hat{x}} =\hat{\mathbf{b}}$.
:::

## Projection Solves Least Squares{.smaller-title}

:::{style="font-size: .9em"}
Let's go back to the case that we can visualize: $A$ is $3 \times 2.$ We have only two columns, $\mathbf{a}_1$ and $\mathbf{a}_2$, so they cannot span $\mathbb{R}^3$.  Hence, it is possible that a vector $\mathbf{b} \in \mathbb{R}^3$ might not lie in $\operatorname{Col}A$:

:::{.center-text}
```{python}
#
fig = ut.three_d_figure((9, 5), 'b is not in Col A', 
                        -15, 15, -15, 15, -15, 15, (6,6), qr = qr_setting)
a2 = np.array([5.0,-13.0,-3.0])
a1 = np.array([1,-2.0,3])
b = np.array([8.0, 8.0, -5.0])
A = np.array([a1, a2]).T
bhat = A @ np.linalg.inv(A.T @ A) @ A.T @ b
fig.text(a1[0], a1[1], a1[2], r'$\bf a_1$', 'a1', size=18)
fig.text(a2[0], a2[1], a2[2], r'$\bf a_2$', 'a2', size=18)
fig.text(b[0], b[1], b[2], r'$\bf b$', 'b', size=18)
#ax.text(1,-4,-10,r'Span{$\bf a,b$}',size=16)
#ax.text(0.2,0.2,-4,r'$\bf 0$',size=20)
# plotting the span of v
fig.plotSpan(a1, a2, 'Green')
fig.plotPoint(a1[0], a1[1], a1[2], 'r')
fig.plotPoint(a2[0], a2[1], a2[2], 'r')
fig.plotPoint(b[0], b[1], b[2], 'b')
#ut.plotPoint3d(ax,0,0,0,'b')
fig.ax.view_init(azim=30, elev=-80.0)
```
:::
:::

## Projection Solves Least Squares{.smaller-title}

:::{style="font-size: .9em"}
We want to find the projection of $\mathbf{b}$ into the column space of $A$:
:::

:::{.center-text}
```{python}
#
fig = ut.three_d_figure((9, 6), 'b-hat is closest to b', 
                        -15, 15, -15, 15, -15, 15, (7,7), qr = qr_setting)
a2 = np.array([5.0,-13.0,-3.0])
a1 = np.array([1,-2.0,3])
b = np.array([8.0, 8.0, -5.0])
A = np.array([a1, a2]).T
bhat = A @ np.linalg.inv(A.T @ A) @ A.T @ b
fig.text(a1[0], a1[1]+.5, a1[2], r'$\bf a_1$', 'a1', size=18)
fig.text(a2[0], a2[1]+.5, a2[2], r'$\bf a_2$', 'a2', size=18)
fig.text(b[0], b[1]+1, b[2], r'$\bf b$', 'b', size=18)
fig.text(bhat[0], bhat[1]+1, bhat[2], r'$A\mathbf{\hat{x}} = \mathbf{\hat{b}}$', 'Ax-hat = b-hat', size=20)
#ax.text(1,-4,-10,r'Span{$\bf a,b$}',size=16)
#ax.text(0.2,0.2,-4,r'$\bf 0$',size=20)
# plotting the span of v
fig.plotSpan(a1, a2, 'Green')
fig.plotPoint(a1[0], a1[1], a1[2], 'r')
fig.plotPoint(a2[0], a2[1], a2[2], 'r')
fig.plotPoint(b[0], b[1], b[2], 'b')
fig.plotPoint(bhat[0], bhat[1], bhat[2], 'b')
fig.plotLine([b, bhat], 'b', '--')
#ut.plotPoint3d(ax,0,0,0,'b')
fig.ax.view_init(azim=30, elev=-80.0)
```
:::

## Normal Equations

:::{style="font-size: .8em"}
How do we find this projection $\hat{b}$?

<br>

Here is the key idea:

> We know that the projection $\hat{\mathbf{b}}$ has the property that $\hat{\mathbf{b}}-\mathbf{b}$ is orthogonal to $\operatorname{Col}A.$

We can decompose $\mathbf{b} = \hat{\mathbf{b}} + \mathbf{z}$ -- so in other words, $\mathbf{z} = \mathbf{b} - \hat{\mathbf{b}}$.

<br>

Suppose $\hat{\mathbf{b}}$ is $\mbox{proj}_{\operatorname{Col}A}\mathbf{b},$ and that $\mathbf{\hat{x}}$ satisfies $A\mathbf{\hat{x}} = \hat{\mathbf{b}}$. 

Hence, $A\mathbf{\hat{x}} - \mathbf{b}$ is orthogonal to $\operatorname{Col}A$ or simply each column of $A$.
:::

## Normal Equations

:::{style="font-size: .8em"}
If $\mathbf{a}_j$ is any column of $A$, then $\mathbf{a}_j^\top (A\mathbf{\hat{x}} - \mathbf{b}) = 0.$

Now, each $\mathbf{a}_j^\top$ is a row of $A^\top$.

<br>

We can collect the equations for all the $\mathbf{a}_j$ as:

$$
\begin{align*}
A^\top (A\mathbf{\hat{x}} - \mathbf{b}) &= {\bf 0} \\
A^\top A\mathbf{\hat{x}} - A^\top\mathbf{b} &= {\bf 0} \\
A^\top A\mathbf{\hat{x}} &= A^\top \mathbf{b}
\end{align*}
$$

<br>

$A^\top A$ is a matrix and $A^\top \mathbf{b}$ is a vector, so this is a standard linear system.  
:::

## Normal Equations

:::{style="font-size: .8em"}
Specifically, that linear system is called the __normal equations__ for $A\mathbf{x} = \mathbf{b}.$

Its solution is denoted by $\mathbf{\hat{x}}$.

<br>

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        The set of least-squares solutions of \(A\mathbf{x} = \mathbf{b}\) is equal to the (nonempty) set of solutions of the normal equations \(A^\top A\mathbf{x} = A^\top \mathbf{b}.\)
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

Proof: see the notes.
:::

## Normal Equations

:::{style="font-size: .8em"}
Let us find the least squares solution of the inconsistent system $A\mathbf{x} = \mathbf{b}$ for
:::

:::{style="font-size: .6em"}
$$
A = \begin{bmatrix}4&0\\0&2\\1&1\end{bmatrix}, \;\;\; \mathbf{b} = \begin{bmatrix}2\\0\\11\end{bmatrix}.
$$
:::

:::{style="font-size: .8em"}
We will use the normal equations $A^\top A\hat{\mathbf{x}} = A^\top \mathbf{b}.$
:::

:::{style="font-size: .6em"}
$$
A^\top A = \begin{bmatrix}4&0&1\\0&2&1\end{bmatrix} \begin{bmatrix}4&0\\0&2\\1&1\end{bmatrix} = \begin{bmatrix}17&1\\1&5\end{bmatrix}.
$$

$$
A^\top \mathbf{b} =  \begin{bmatrix}4&0&1\\0&2&1\end{bmatrix} \begin{bmatrix}2\\0\\11\end{bmatrix} = \begin{bmatrix}19\\11\end{bmatrix}.
$$
:::

## Normal Equations

:::{style="font-size: .8em"}

The normal equations are: $\begin{bmatrix}17&1\\1&5\end{bmatrix}\begin{bmatrix}\hat{x}_1\\\hat{x}_2\end{bmatrix} = \begin{bmatrix}19\\11\end{bmatrix}.$

We can solve this system using row operations, or by inverting $A^\top A$:

$$
(A^\top A)^{-1} = \frac{1}{84}\begin{bmatrix}5&-1\\-1&17\end{bmatrix}
$$

<!-- And we can then solve $A^\top A\hat{\mathbf{x}} = A^\top \mathbf{b}$ as -->

$$
\mathbf{\hat{x}} = (A^\top A)^{-1}A^\top \mathbf{b} = \frac{1}{84}\begin{bmatrix}5&-1\\-1&17\end{bmatrix}\begin{bmatrix}19\\11\end{bmatrix} = \frac{1}{84}\begin{bmatrix}84\\168\end{bmatrix} = \begin{bmatrix}1\\2\end{bmatrix}.
$$

We conclude that $\mathbf{\hat{x}} = \begin{bmatrix}1\\2\end{bmatrix}$ is the vector that minimizes $\Vert A\mathbf{x} -\mathbf{b}\Vert,$ and is the least-squares solution of $A\mathbf{x} = \mathbf{b}$.
:::

## Normal Equations

:::{style="font-size: .8em"}
The normal equations _always_ have a solution.  
</br>

However, the solution does not have to be unique. There can be multiple solutions that _all_ minimize $\Vert A\mathbf{x} - \mathbf{b}\Vert.$

</br>

We know that a linear system has multiple solutions when there are columns that are not pivot columns. Equivalently, when $A \bf{\hat{x}} = \bf{\hat{b}}$ has multiple solutions, the columns of $A$ are linearly dependent.
:::

## Normal Equations

:::{style="font-size: .8em"}
<!-- We know that a linear system has multiple solutions when there are columns that are not pivot columns. Equivalently, when $A \bf{\hat{x}} = \bf{\hat{b}}$

Here is a picture of what is going on.   -->

In this case, $A$ is $3 \times 3$. Note that $\operatorname{Col}A$ is only two-dimensional because the three columns are linearly dependent.

:::{.center-text}
```{python}
#
fig = ut.three_d_figure((9, 7), 'Multiple Solutions to the Normal Equations', 
                        -15, 15, -15, 15, -15, 15, (4,4), qr = qr_setting)
a2 = np.array([5.0,-13.0,-3.0])
a1 = np.array([1,-2.0,3])
a3 = -2*a1 + a2
b = np.array([6.0, 8.0, -5.0])
A = np.array([a1, a2]).T
bhat = A.dot(np.linalg.inv(A.T.dot(A))).dot(A.T).dot(b)
fig.text(a1[0], a1[1], a1[2], r'$\bf a_1$', 'a_1', size=20)
fig.text(a2[0], a2[1], a2[2], r'$\bf a_2$', 'a_2', size=20)
fig.text(a3[0], a3[1], a3[2], r'$\bf a_3$','a_3', size=20)
fig.text(b[0], b[1], b[2], r'$\bf b$', 'b', size=20)
fig.text(bhat[0], bhat[1], bhat[2], r'$A\mathbf{\hat{x}} = \mathbf{\hat{b}}$', 'b-hat', size=20)
#ax.text(1,-4,-10,r'Span{$\bf a,b$}',size=16)
#ax.text(0.2,0.2,-4,r'$\bf 0$',size=20)
# plotting the span of v
fig.plotSpan(a1, a2, 'Green')
fig.plotPoint(a1[0], a1[1], a1[2], 'r')
fig.plotPoint(a2[0], a2[1], a2[2], 'r')
fig.plotPoint(a3[0], a3[1], a3[2], 'r')
fig.plotPoint(b[0], b[1], b[2], 'b')
fig.plotPoint(bhat[0], bhat[1], bhat[2], 'b')
fig.plotLine([b, bhat], 'b', '--')
#ut.plotPoint3d(ax,0,0,0,'b')
fig.ax.view_init(azim=26.0,elev=-77.0)
```
:::


The orthogonal projection $\hat{\mathbf{b}}$ is always unique.   Some least squares problem have multiple solutions, because there are _multiple ways_ to construct $\hat{\mathbf{b}}$.

:::

## Normal Equations

:::{style="font-size:.8em"}

Let's find a least-squares solution for $A\mathbf{x} = \mathbf{b}$ for
:::

:::{style="font-size:.6em"}
$$
A = \begin{bmatrix}1&1&0&0\\1&1&0&0\\1&0&1&0\\1&0&1&0\\1&0&0&1\\1&0&0&1\end{bmatrix},\;\;\; \mathbf{b} = \begin{bmatrix}-3\\-1\\0\\2\\5\\1\end{bmatrix}.
$$
:::

:::{style="font-size:.8em"}
We compute the components of the normal equations.
:::

:::{style="font-size:.6em"}
$$
A^{\top} A = \begin{bmatrix}1&1&1&1&1&1\\1&1&0&0&0&0\\0&0&1&1&0&0\\0&0&0&0&1&1\end{bmatrix}\begin{bmatrix}1&1&0&0\\1&1&0&0\\1&0&1&0\\1&0&1&0\\1&0&0&1\\1&0&0&1\end{bmatrix} = \begin{bmatrix}6&2&2&2\\2&2&0&0\\2&0&2&0\\2&0&0&2\end{bmatrix},
$$
:::

## Normal Equations

:::{style="font-size:.6em"}

$$
A^{\top} \mathbf{b} = \begin{bmatrix}1&1&1&1&1&1\\1&1&0&0&0&0\\0&0&1&1&0&0\\0&0&0&0&1&1\end{bmatrix}\begin{bmatrix}-3\\-1\\0\\2\\5\\1\end{bmatrix} = \begin{bmatrix}4\\-4\\2\\6\end{bmatrix}.
$$
:::

:::{style="font-size:.8em"}
To solve $A^{\top} A\hat{\mathbf{x}} = A^{\top} \mathbf{b},$ we'll use row reduction.  The augmented matrix $[A^{\top} A \vert A^{\top} \mathbf{b}]$ is:
:::

:::{style="font-size:.6em"}
$$
\left[\begin{array}{cccc|c}6&2&2&2&4\\2&2&0&0&-4\\2&0&2&0&2\\2&0&0&2&6\end{array}\right] \sim \left[\begin{array}{cccc|c}1&0&0&1&3\\0&1&0&-1&-5\\0&0&1&-1&-2\\0&0&0&0&0\end{array}\right]
$$
:::

:::{style="font-size:.8em"}

In the RREF, there are only 3 pivot columns, so there is a free variable.
:::

## Normal Equations

:::{style="font-size:.8em"}
<!-- To solve $A^{\top} A\hat{\mathbf{x}} = A^{\top} \mathbf{b},$ we'll use row reduction.  The augmented matrix $[A^{\top} A \vert A^{\top} \mathbf{b}]$ is:

$$
\left[\begin{array}{cccc|c}6&2&2&2&4\\2&2&0&0&-4\\2&0&2&0&2\\2&0&0&2&6\end{array}\right] \sim \left[\begin{array}{cccc|c}1&0&0&1&3\\0&1&0&-1&-5\\0&0&1&-1&-2\\0&0&0&0&0\end{array}\right]
$$

<br>

In the RREF, there are 4 column vectors, but only the first three are linearly independent. The last column can be written as a linear combination of them.

<br> -->

From the RREF we see that only the first three columns of $A^\top A$ are linearly independent. The last column can be written as a linear combination of them.

<br>

The columns of $A^\top A$ are linearly dependent, because the columns of $A$ are linearly dependent.

<br>

You can see this as follows: if $A$ has a non-trivial null space, then $A^\top A$ also has a nontrival null space.
:::

## Normal Equations

:::{style="font-size:.8em"}
The general solution of the normal equations is $x_1 = 3-x_4,$ $x_2 = -5+x_4,$ $x_3 = -2 + x_4,$ and $x_4$ is free.

<br>

Hence, the general least-squares solution of $A\hat{\mathbf{x}} = \mathbf{b}$ has the form

$$
\mathbf{\hat{x}} = \begin{bmatrix}3\\-5\\-2\\0\end{bmatrix} + x_4\begin{bmatrix}-1\\1\\1\\1\end{bmatrix}.
$$
:::

## Normal Equations

:::{style="font-size:.8em"}

Here is a theorem that allows us to identify when there are multiple least-squares solutions.

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        Let \(A\) be an \(m\times n\) matrix.  The following statements are equivalent:
<ol start=1>
<li> The equation \(A\mathbf{x} = \mathbf{b}\) has a unique least-squares solution for each \(\mathbf{b}\) in \(\mathbb{R}^m.\)</li>
<li>The columns of \(A\) are linearly independent.</li>
<li>The matrix \(A^\top A\) is invertible.</li>

When these statements are true, the least-squares solution \(\mathbf{\hat{x}}\) is given by:

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\(\mathbf{\hat{x}} = (A^\top A)^{-1}A^\top \mathbf{b}.\)
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

:::

## Finding $\hat{\mathbf{b}}$ directly

:::{style="font-size: .8em"}
When $A^\top A$ is invertible, we can put together the two equations
$\mathbf{\hat{x}} = (A^\top A)^{-1}A^\top \mathbf{b}$ and $A\mathbf{\hat{x}} = \hat{\mathbf{b}}$ to get:

$$
\hat{\mathbf{b}} = A(A^\top A)^{-1}A^\top \mathbf{b}.
$$

Let's stop and look at this another way.  Up until now we have seen how to project a point onto a line, or on to a subspace with an orthogonal basis.  

<br>

This equation shows how to project onto a subspace (namely $\operatorname{Col} A$) given an __arbitrary__ basis.  This is a general formula that can be very useful.
:::

## Key Ideas
:::{style="font-size: .8em"}
- The least squares solution $\hat{\mathbf{x}}$ minimizes $||A\mathbf{x} - \mathbf{b}||^2,$ the sum of squared errors.

- The best $\hat{\mathbf{x}}$ comes from the normal equations $A^\top A \hat{\mathbf{x}} = A^\top \mathbf{b}.$

- Normal equations always have a solution, but it is not unique when the solumns of $A$ are linearly dependent.
:::



