---
title: \small Existence and Uniqueness<br>of Solutions
author: "CDS DS-121<br>Boston University"
format: 
    revealjs:
        math: true
        css: 
        - styles.css
        html-math-method: mathjax
include-in-header:
  - text: |
      <style>
      #title-slide .title {
        font-size: 2em;
        #color: #b22222;
      }
      </style>
      
# Fun way to change size of title slide and even in color! WOW!!
---


## Learning Objectives

:::{style="font-size: .8em"}
Today's lecture will focus on the solutions of linear systems. We will talk about the number of solutions of $A\bf{x}=\bf{b}$ when both $A$ and $\bf{b}$ are given, and also when only $A$ is given.

:::{.fragment}
In addition, we will relate the number of solutions of $A\bf{x}=\bf{b}$ to the concept of span.
:::
:::

<!-- ## Consistency -->

<!-- :::{style="font-size:.8em"}
Recall that any system of linear equations has either 0, 1, or infinitely many solutions.

:::{.fragment}
A system of equations is __inconsistent__ (i.e., has 0 solutions) if its augmented matrix $A$ has a pivot position in the final column (i.e., to the right of the bar). In other words, once $A$ is converted into reduced row echelon form, it contains a row that looks like this:

$$
\left[\begin{array}{cccccc|c}
0&0&0& \cdots &0&0&\blacksquare
\end{array}\right],
$$

where $\blacksquare$ denotes a non-zero entry. Otherwise, the system is consistent.
:::
::: -->

## Consistency and Uniqueness

:::{style="font-size: .8em"}
Recall that any system of linear equations has either 0, 1, or infinitely many solutions. We call the system _inconsistent_ when it has _no solutions_. 


This is the case when during Gauss-Jordan elimination we obtain the augmented matrix with a row that looks like this:
$$
\left[\begin{array}{cccccc|c}
0&0&0& \cdots &0&0&\blacksquare
\end{array}\right],
$$

where $\blacksquare$ denotes a non-zero entry. 

Otherwise, the system is consistent.

If a system is consistent, it has a _unique solution_ if and only if it has _no free variables_. That is, each column left from the partition line contains a pivot.

Otherwise, a consistent system has infinitely many solutions.


<!-- :::{.fragment}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        If a reduced row echelon matrix has a row like the one shown above, why is it inconsistent?
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```
::: -->
:::

<!-- ## Uniqueness

:::{style="font-size: .8em"}
If a system is consistent, it has a _unique solution_ if and only if it has _no free variables_. That is, each column left from the partition line contains a pivot.

Otherwise, a consistent system has infinitely many solutions.

::: -->

<!-- ## Consistency and Uniqueness

:::{style="font-size: .6em"}
__Example 1.__ Consider the following augmented matrix and its associated echelon and reduced echelon forms.

$$
\begin{array}{ccccc}
\left[
\begin{array}{rr|r}
        0 & 1  & 1\\
        1 & 1  & 2\\
        1 & -1 & 3
\end{array}
\right]
& \longrightarrow &
\left[
\begin{array}{rr|r}
        1 & 1  & 2\\
        0 & 1  & 1\\
        0 & 0  & 3
\end{array}
\right]
& \longrightarrow &
\left[
\begin{array}{rr|r}
        1 & 0  & 1\\
        0 & 1  & 1\\
        0 & 0  & 1
\end{array}
\right]
\end{array}
$$

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        Does this linear system have 0, 1, or infinitely many solutions?
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

:::{.fragment}
This linear system is __inconsistent__ - that is, it has 0 solutions. There are a few ways to observe this:

- The final equation states that $0 = 3$, which can never be true for any choice of $x_1$, $x_2$, and $x_3$.
- The third row has a pivot position in the final column.
:::
::: -->

## Consistency and Uniqueness

:::{style="font-size: .8em"}

Here is an augmented matrix in reduced echelon form.

$$
\left[\begin{array}{rrr|r}
1&0&-5&1\\
0&1&1&4\\
0&0&0&0
\end{array}\right]
$$

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        This system is consistent. Is the solution unique?
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

<!-- :::{.fragment}
The associated system of equations is

$$
\begin{array}{rrrrr}
x_1 & & -5x_3 &=& 1\\
&x_2 & +x_3 &=& 4\\
&&0&=&0\\
\end{array}
$$

::: -->

:::{.fragment}
Variables $x_1$ and $x_2$ correspond to pivot columns, so $x_1$ and $x_2$ are basic variables. The remaining variable $x_3$ is free. Hence, there are infinitely many solutions.
:::
:::

## Consistency and Uniqueness

:::{style="font-size: .8em"}
Each solution corresponds to one particular value of $x_3$.  

For instance, 

* when $x_3 = 0,$ the solution is $(1,4,0);$ 
* when $x_3 = 1,$ the solution is $(6,3,1).$

These are _parametric_ descriptions of solutions sets.  The free variables act as parameters.  

<!-- :::{.fragment}
So solving a system amounts to either:

* finding a parametric description of the solution set, or
* determining that the solution set is empty.
::: -->
:::

## Consistency and Uniqueness

:::{style="font-size: .8em"}
Geometrically, the solution set to this system is a line in $\mathbb{R}^3$.
:::

<div style="text-align: center;">
  <video width="700" autoplay loop muted>
    <source src="/figures/Fig3.3.mp4" type="video/mp4">
  </video>
</div>

<!-- ## Consistency and Uniqueness

:::{style="font-size: .5em"}

__Example.__ Here is an augmented matrix already in reduced row echelon form.

$$
\left[\begin{array}{rrrrr|r}
1 & 0 & -2 & 3 & 0 & -24\\
0 & 1 & -2 & 2 & 0 & -7\\
0 & 0 & 0 & 0 & 1 & 4
\end{array}\right]
$$

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        What are the basic and free variables in this augmented matrix? How many solutions are there?
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

:::{.fragment}
The pivot columns are 1, 2, and 5. Therefore, $x_1$, $x_2$, and $x_5$ are basic variables.

The remaining variables $x_3$ and $x_4$ are free variables: they can take on any value. Hence, the system has _infinitely many solutions_.

For any choice of $x_3$ and $x_4,$ we can calculate the basic variables using the equations from reduced row echelon form and moving the $x_3$ and $x_4$ terms to the right-hand side of the equations:
\begin{align*}
x_1 &= -24 + 2x_3 - 3x_4 \\
x_2 &= -7 + 2x_3 - 2x_4 \\
x_5 &= 4
\end{align*}
:::

:::{.fragment}
Following this approach: if I give you a matrix $A$ and vector ${\bf b},$ you can determine whether the matrix equation $A {\bf x} = {\bf b}$ is consistent (i.e., has at least one solution).
:::
::: -->

## Consistency Based on Matrix $A$ {.smaller-title}

:::{style="font-size: .9em"}
Let us ask a more general question, which is solely about the matrix $A \in \mathbb{R}^{m \times n}.$ 

> Does $A{\bf x} = {\bf b}$ have a solution for _every possible_ vector ${\bf b} \in \mathbb{R}^m$?

:::{.fragment}
__Example.__ Let $A = \left[\begin{array}{rrr}1&3&4\\-4&2&-6\\-3&-2&-7\end{array}\right]$ and ${\bf b} = \left[\begin{array}{r}b_1\\b_2\\b_3\end{array}\right].$  

We can use Gauss-Jordan elimination to see if the equation $A{\bf x} = {\bf b}$ is consistent for all possible $b_1, b_2, b_3.$ 

$$
\left[\begin{array}{rrr|c}1&3&4&b_1\\-4&2&-6&b_2\\-3&-2&-7&b_3\end{array}\right] \sim \left[\begin{array}{rrr|c}1&3&4&b_1\\0&14&10&b_2+4b_1\\0&0&0&b_3+3b_1-\frac{1}{2}(b_2 + 4b_1)\end{array}\right].
$$
:::

:::

## Consistency Based on Matrix $A$ {.smaller-title}

:::{style="font-size: .9em"}
<!-- $$
\left[\begin{array}{rrr|c}1&3&4&b_1\\-4&2&-6&b_2\\-3&-2&-7&b_3\end{array}\right] \sim \left[\begin{array}{rrr|c}1&3&4&b_1\\0&14&10&b_2+4b_1\\0&0&0&b_3+3b_1-\frac{1}{2}(b_2 + 4b_1)\end{array}\right].
$$ -->

<!-- $$
\sim \left[\begin{array}{rrr|c}1&3&4&b_1\\0&14&10&b_2+4b_1\\0&0&0&b_3+3b_1-\frac{1}{2}(b_2 + 4b_1)\end{array}\right].
$$ -->

The third entry in the column 4 is $b_1 -\frac{1}{2}b_2+ b_3.$ This expression can be nonzero. 

For example, take $b_1 = 1, b_2 = 1, b_3 = 1.$ Then the lower right entry is 1.5.  This gives a row of the form $0 = 1.5$, which indicates an inconsistent system.  

Hence, $A{\bf x} = {\bf b}$ is _not_ consistent for all possible $b_1, b_2, b_3.$

:::{.fragment}
It fails to be consistent for all $\bf b$ because the echelon form of $A$ has a row of zeros. For instance, the augmented matrix might have reduced to:

$$
\left[\begin{array}{rrr|c}1&3&4&0\\0&14&10&0\\0&0&0&1\end{array}\right].
$$
:::

:::{.fragment}
If $A$ had a pivot in all three rows, an echelon form of the augmented matrix could not have a row indicating $0 = k$.
:::

:::

<!-- ## Consistency Based on Matrix $A$ {.smaller-title}

:::{style="font-size: .8em"}
Here is the echelon form of $A$ (note we are talking only about the coefficient matrix $A$ here, not the augmented matrix):

$$
\left[\begin{array}{rrr}1&3&4\\0&14&10\\0&0&0\end{array}\right].
$$

:::{.fragment}
The equation $A{\bf x} = {\bf b}$ fails to be consistent for all $\bf b$ because the echelon form of $A$ has a row of zeros. For instance, the augmented matrix might have reduced to:

$$
\left[\begin{array}{rrr|c}1&3&4&0\\0&14&10&0\\0&0&0&1\end{array}\right].
$$
:::

:::{.fragment}
If $A$ had a pivot in all three rows, an echelon form of the augmented matrix could not have a row indicating $0 = k$ (and so the augmented column does not matter).
:::
::: -->

<!-- ## Consistency Based on Matrix $A$ {.smaller-title}

:::{style="font-size: .9em"}

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        When <em>is</em> \(A{\bf x} = {\bf b}\) consistent?
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

:::{.fragment}
When $b_1 -\frac{1}{2}b_2+ b_3 = 0$ (i.e., the last row of the augmented matrix all zeros). This is a single equation in three unknowns, so it defines a plane through the origin in $\mathbb{R}^3.$
:::

::: -->

## Consistency Based on Matrix $A$ {.smaller-title}

<!-- Was having trouble with putting video in fragment, so just did the easy solution of copying the slide... : ( -->

:::{style="font-size: .8em"}

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        For what entries of \({\bf b}\) <em>is</em> \(A{\bf x} = {\bf b}\) consistent?
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

:::{.fragment}
When $b_1 -\frac{1}{2}b_2+ b_3 = 0$ (this makes the last row of the augmented matrix all zeros). This is a single equation in three unknowns, so it defines a plane through the origin in $\mathbb{R}^3.$



<div style="text-align: center;">
  <video width="400" autoplay loop muted>
    <source src="/figures/Fig14.1.mp4" type="video/mp4">
  </video>
</div>

:::
:::

## Relationship to Span

:::{style="font-size: .8em"}
The set of points that makes $b_1 - \frac{1}{2}b_2 + b_3 = 0$ is the set of $\bf b$ values that makes $A{\bf x} = {\bf b}$ consistent.

:::{.fragment}
So we have determined that Span$\{\bf a_1, a_2, a_3\}$ is the same point set as $b_1 - \frac{1}{2}b_2 + b_3 = 0$.

That means that Span$\{\bf a_1, a_2, a_3\}$ is a _plane_ in this case -- it is a system of 1 equation in 3 variables.

In the figure, $\bf a_1, a_2,$ and $\bf a_3$, you can see that all three points and the origin $\bf 0$, lie in the same plane.
:::

:::{.fragment}
Now, in the most general case, four points will _not_ lie in a plane.  In other words, the span of three vectors in $\mathbb{R}^3$ can be the whole space $\mathbb{R}^3$.
:::
:::

## Consistency and Span

:::{style="font-size: .8em"}

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        Let \(A\) be an \(m \times n\) matrix.  Then the following statements are logically equivalent.  
            <ol>
            <li> For each \(\bf b\) in \(\mathbb{R}^m,\) the equation \(A{\bf x} = {\bf b}\) has a solution.</li>
            <li> Each \(\bf b\) in \(\mathbb{R}^m\) is a linear combination of the columns of \(A.\)</li>
            <li> The columns of \(A\) span \(\mathbb{R}^m\).</li>
            <li> \(A\) has a pivot position in every row. </li>
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

<!-- :::{.fragment}
Notice that we started by thinking about a matrix equation (and an augmented matrix,) but we ended by making statements about $A$ alone.
::: -->
:::

## Key Ideas

:::{style="font-size: .8em" .incremental}

- When a system is inconsistent, the Gauss-Jordan elimination of the corresponding augmented matrix will lead to a row with all zeros left from the partition line and a non-zero value right from the partition line.

- A consistent system with no free variables has a unique solution. Otherwise, there are infinitely many solutions.

- When $A \bf {x} = \bf {b}$ has a solution for each $\bf b \in \mathbb{R}^m,$ the columns of $A$ span $\mathbb{R}^m.$
:::