---
title: "Linear Dependence"
author: "CDS DS-121<br>Boston University"
format: 
    revealjs:
        math: true
        css: 
        - styles.css
        html-math-method: mathjax
        highlight-style: github
        slide-number: true
        show-slide-number: all
        chalkboard: true

---

## Collinearity
::::{style="font-size:.8em"}
Social media influencer performance: 

- Follower count
- Likes received on posts
- Video views
- Estimated monthly income

:::{.center-text}
```{python}
import pandas as pd  

# Load the dataset and perform the analysis
data = pd.read_csv('data/influencer_dataset.csv')
print(data.head(6))
```
:::
Understanding collinearity helps us avoid misleading models by ensuring each feature adds unique value to predictions.
:::

## Learning Objectives
::::{style="font-size:.8em"}
- Linear dependence and independence:
    - Definition
    - Algebraic and geometric views
- Connection to linear combinations
- Connection to span
::::

## Linear Dependence

::::{style="font-size:.8em"}
Let's consider a consistent system of equations $x_1\mathbf{a_1} + x_2\mathbf{a_2}=\mathbf{a_3}$, meaning that $\mathbf{a_3}$ is in the span of $\mathbf{a_1}$ and $\mathbf{a_2}$. 

::::

<video width="1000" autoplay loop muted>
  <source src="/figures/Fig2.9.mp4" type="video/mp4">
</video>




## Linear Dependence

:::{style="font-size:.8em"}
Although $\mathbf{0, a_1, a_2,}$ and $\mathbf{a_3}$ are in $\mathbb{R}^3,$ they lie within the same two-dimensional plane.

Such relationship among the vectors is known as linear dependence.

<br><br>

Before stating the formal definition, let’s build some intuition about what this means.

We observe the following:

> The plane defined by vectors $\mathbf{a_1,a_2,}$ and $\mathbf{a_3}$ happens to include the origin $\mathbf{0}$.


:::

## Linear Dependence

::::{style="font-size:.8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
         <span class="label">Linear dependence</span>
        A set of vectors \(\{\mathbf{v_1,\dots,v_p}\}\) all of which are in \(\mathbb{R}^n\) is said to be <b>linearly dependent</b> if the vector equation<br>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\(x_1\mathbf{v_1}+\dots+x_p\mathbf{v_p}=\mathbf{0}\) <br>
        has a solution \(x_1=c_1,\dots,x_p=c_p\) where <em>at least</em> one of the scalar weights \(c_i\) is nonzero.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))

```
<div style="margin-bottom: 0.5em;"> </div> 

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
         <span class="label">Linear independence</span>
        The set \(\{\mathbf{v_1,\dots,v_p}\}\) is said to be <b>linearly independent</b> if the vector equation<br>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\(x_1\mathbf{v_1}+\dots+x_p\mathbf{v_p}=\mathbf{0}\)
        <br>
        has <em>only</em> the trivial solution \(x_1=0,\dots,x_p=0.\)
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))

```

::::

## Linear Dependence
::::{style="font-size:.8em"}
__Example__: Consider vectors
$\small \mathbf{u} = \begin{bmatrix} 1 \\ -1\\ 0 \end{bmatrix},
\mathbf{v} = \begin{bmatrix} 0 \\ 1\\ -1 \end{bmatrix},
\mathbf{w} = \begin{bmatrix} -1 \\ 0\\ 1 \end{bmatrix}.$

We can see that $$\small \mathbf{w} = \begin{bmatrix} -1 \\ 0\\ 1 \end{bmatrix} = - \mathbf{u} - \mathbf{v}.$$

Equivalently, we can write $\small \mathbf{u} + \mathbf{v} + \mathbf{w} = \mathbf{0}.$<br>
Hence, the vectors are linearly dependent.

Note: all three vectors have components adding to zero. Hence, $\small x_1+x_2+x_3=0$ is the equation for the plane containing all combinations of $\small \mathbf{u}$ and $\small \mathbf{v}.$ By including $\small \mathbf{w}$ we get _**no new points**_ because $\small \mathbf{w}$ is already on that plane.

::::

## Linear Dependence

::::{style="font-size:.8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        For each set of vectors specify if they are dependent or independent.
        <ol type="a">
            <li>\(\Big\{{\small\begin{bmatrix}1 \\ 0 \end{bmatrix},\begin{bmatrix}0 \\ 1 \end{bmatrix} }\Big\}\)</li>
            <li>\(\Big\{{\small\begin{bmatrix}1 \\ 1 \end{bmatrix},\begin{bmatrix}-1 \\ -1 \end{bmatrix} }\Big\}\)</li>
            <li>\(\Big\{{\small\begin{bmatrix}1 \\ 1 \end{bmatrix},\begin{bmatrix}0 \\ 0 \end{bmatrix} }\Big\}\)</li>
            <li>\(\Big\{{\small\begin{bmatrix}-2 \\ 0 \end{bmatrix},\begin{bmatrix}1 \\ -1 \end{bmatrix},\begin{bmatrix}0 \\ 1 \end{bmatrix} }\Big\}\)</li>
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))

```
<!-- 
    a independent
    b dependent
    c dependent : )
    d dependent? -->
::::

:::{.notes}
a. Independent

b. 1 v_1 + 1 v_2 = 0

c. 0 v_1 + 1 v_2 = 0

d. (1/2)v_1 + v_2 + v_3 =0

Note: You can't have more than n linearly independent directions in an n-dimensional space. You can think of Rn
  as having n slots to store independent directions. Once you fill those slots with n linearly independent vectors, any new vector you add must be a combination of the ones already there — because there's no room for a new independent direction.
:::

## Link to Linear Combinations 

::::{style="font-size:.8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>  <span class="label">Theorem</span>
        <b></b> Let \(S\) be a set of two or more vectors: \(S=\{\mathbf{v_1,\dots,v_p}\}.\) At least one of the vectors in \(S\) is a linear combination of the others if and only if \(S\) is linearly dependent.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

<!-- Even if small amount of text after, is it better to just fragment the big chunk, then reveal little one? Not wanting to show too much at once. -->

:::{.fragment}
**Proof.** In the 'if' direction, we assume that there exists one vector in $S$ that is a linear combination of the others. We need to prove that $S$ is linearly dependent. 

Since $S$ is an unordered set, the labeling of indices is arbitrary. Let's relabel the indices in order to make this vector $\mathbf{v_p}$.

By the definition of linear combination, this means that there exist scalars $c_1,c_2,\dots,c_{p-1}$ such that:
$$
c_1\mathbf{v_1}+\cdots+c_{p-1}\mathbf{v_{p-1}} = \mathbf{v_p}.
$$

:::
::::

:::{.notes}
$P \iff Q$

Easy proofs during classes, even easier proofs on the exams.

MANY proofs in DS320.

Definition linear combination:

v_p = a_1v_1 + a_2v_2 ... + a_{p-1}v_{p-1}

Definition linear dependence:

b_1v_1+b_2v_2 + ... + b_pv_p = 0 has a non-trivial solution

:::

## Link to Linear Combinations

::::{style="font-size:.8em;"}
We subtract $\mathbf{v_p}$ from both sides of this equation:

$$
c_1\mathbf{v_1}+\cdots+c_{p-1}\mathbf{v_{p-1}}-\mathbf{v_p} = \mathbf{0}.
$$

Not all the coefficients are zero (in particular, the coefficient of $\mathbf{v_p}$ is $-1$). Thus, the vectors are linearly dependent.


:::{.fragment}
Now, we consider the "only if" part:

Assume $S$ is linearly dependent. Then $c_1\mathbf{v_1}+\cdots+c_{p}\mathbf{v_{p}} = \mathbf{0}$ and at least one of the $c_i$ is nonzero.

Pick one of the nonzero $c_i$, and rearranging it, we get:
<!-- maybe instead $, rearrange it, and we get:
or $, rearranging it gets us: ? -->
$$
\mathbf{v_i}=-(c_1/c_i)\mathbf{v_1}-\cdots-(c_p/c_i)\mathbf{v_p}.
$$

Thus, there is at least one vector that is a linear combination of the others.
:::
::::

## Link to Span

::::{style="font-size:.8em"}

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>
        <p>  <span class="label">Spanning set</span>
        Let \(V\) be a subset of \(\mathbb{R}^d\). A <b>spanning set</b> for \(V\) is a set of vectors such that any vector in \(V\) can be expressed as a linear combination of the vectors in this set.
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

Let's explore the connection between spanning sets and linear dependence.

We'll start with two linearly independent vectors $\mathbf{u}={\small\begin{bmatrix}3\\1\\0\end{bmatrix}}$ and $\mathbf{v}={\small\begin{bmatrix}1\\6\\0\end{bmatrix}}.$

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        What subset of \(\mathbb{R}^3\) is spanned by \(\mathbf{u}\) and \(\mathbf{v}\)?
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

::::

:::{.notes}
generating set 

Building blocks -> spanning set

Building -> span
:::

## Link to Span

<div style="text-align: center;">
  <video width="600" autoplay loop muted>
    <source src="/figures/Fig2.10.mp4" type="video/mp4">
  </video>
</div>

## Link to Span 

::::{style="font-size:.8em"}
Next, let us explain why a non-zero vector $\mathbf{w}$ is in $\text{Span}\{\mathbf{u},\mathbf{v}\}$ if and only if $\{\mathbf{u,v,w}\}$ is linearly dependent.

<br>

If $\mathbf{w}$ is in $\text{Span}\{\mathbf{u},\mathbf{v}\}$, then $\mathbf{w}$ is a linear combination of $\mathbf{u}$ and $\mathbf{v}$.

So $\{\mathbf{u,v,w}\}$ is linearly dependent (by the theorem we just proved).

<br>

On the other hand, $\{\mathbf{u,v,w}\}$ is linearly dependent, there exists $c_1,c_2,$ and $c_3,$ not all zero, such that

$$
c_1\mathbf{u} + c_2\mathbf{v} + c_3\mathbf{w} = \mathbf{0}
$$


::::

## Link to Span 

::::{style="font-size:.75em"}

This implies that there are two options for $c_3$:

1. $c_3=0$ and
2. $c_3\neq 0.$

Let us consider both options.

1. If $c_3=0$, then $c_1\mathbf{u} + c_2\mathbf{v} = \mathbf{0}.$ However, this is not possible, because $\mathbf{u}$ and $\mathbf{v}$ are linearly independent. Thus, $c_3\neq0.$

2. If $c_3\neq0$, then we can express $\mathbf{w}$ as

$$
\mathbf{w} = -\left(\frac{c_1}{c_3}\right) \mathbf{u} - \left(\frac{c_2}{c_3}\right) \mathbf{v}.
$$

From here it follows that $\mathbf{w}$ is in $\text{Span}\{\mathbf{u},\mathbf{v}\}.$

::::

## Link to Span

<div style="text-align: center;">
  <video width="600" autoplay loop muted>
    <source src="/figures/Fig2.10.mp4" type="video/mp4">
  </video>
</div>

## Link to Span 

<div style="text-align: center;">
  <video width="600" autoplay loop muted>
    <source src="/figures/Fig2.11.mp4" type="video/mp4">
  </video>
</div>

## Link to Span

::::{style="font-size:.75em"}
The above example can be expanded from $3$ to $p$ $(p>3)$ vectors.


- If a set of vectors $\{\mathbf{v_1,v_2,\dots,v_p}\}$ is linearly dependent, then at least one of them lies wihin the span of the others.

- At the same time, if one vector in the set $\{\mathbf{v_1,v_2,\dots,v_p}\}$ lies within the span of the others, then the set is linearly dependent.


```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>
        Which number \(c\) gives dependent vectors?
        <ol type="a">
            <li> \( \small \begin{bmatrix} 1 \\ 3 \\ 7 \end{bmatrix}, \begin{bmatrix} 1 \\ 2 \\ 4 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ c \end{bmatrix}\)</li>
            <li> \( \small \begin{bmatrix} c \\ 2 \\ 3 \end{bmatrix}, \begin{bmatrix} c \\ 1 \\ 3 \end{bmatrix}, \begin{bmatrix} c \\ 5 \\ 6 \end{bmatrix}\)
            </li>
        </p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))

```


::::
:::{.notes}
a. c=3: vec 3 = vec 1− vec 2

b. c=0: vec 3 = 3 (vec 1)− vec 2
:::

