---
title: "Basis and Dimension"
author: "CDS DS-121<br>Boston University"
format: 
    revealjs:
        math: true
        css: 
        - styles.css
        html-math-method: mathjax
        highlight-style: github
        slide-number: true
        show-slide-number: all
        chalkboard: true
---

## Learning Objectives

:::{style="font-size: .8em"}
- Review bases and dimensions
- Basis for a nullspace
- Basis for a column space
- Matrix rank
- Rank-nullity theorem  
- New statements for IMT
:::

## Basis

:::{style="font-size: .8em"}
Consider the subspace $H$ of $\mathbb{R}^3$ described by $\text{Span}\{\mathbf{a}_1, \mathbf{a}_2, \mathbf{a}_3\}$ with
:::
:::{style="font-size: .6em"}

$$
{\bf a_1} = \begin{bmatrix} -8 \\ 8 \\ 5 \end{bmatrix}, \quad
{\bf a_2} = \begin{bmatrix} 3 \\ 2 \\ -2 \end{bmatrix}, \quad
{\bf a_3} = \begin{bmatrix} 7.5 \\ 5 \\ -5 \end{bmatrix} = 2.5 {\bf a_2}.
$$

:::{.center-text}
```{python}
import laUtilities as ut
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

qr_setting = None

fig = ut.three_d_figure((7, 4), fig_desc = 'H = Span{a1, a2, a3}',
                        xmin = -10, xmax = 10, ymin = -10, ymax = 10, zmin = -10, zmax = 10, qr = qr_setting)
a1 = [-8.0, 8.0, 5.0]
a2 = [3.0,  2.0, -2.0]
a3 = 2.5 * np.array(a2)
fig.text(a1[0]+.5, a1[1]+.5, a1[2]+.5, r'$\bf a_1$', 'a_1', size=18)
fig.text(a3[0]+.5, a3[1]+.5, a3[2]+.5, r'$\bf a_3$', 'a_3', size=18)
fig.text(a2[0]+.5, a2[1]+.5, a2[2]+.5, r'$\bf a_2$', 'a_2', size=18)
fig.plotSpan(a1, a2,'Green')
fig.plotPoint(a1[0], a1[1], a1[2],'r')
fig.plotPoint(a3[0], a3[1], a3[2],'r')
fig.plotPoint(a2[0], a2[1], a2[2],'r')
# fig.plotPoint(a3[0], a3[1], a3[2],'r')
fig.text(0.1, 0.1, -3, r'$\bf 0$', '0', size=12)
fig.plotPoint(0, 0, 0, 'b')
fig.set_title(r'$H$ = Span$\{{\bf a}_1, {\bf a}_2, {\bf a}_3\}$')
fig.text(9, -9, -7, r'H', 'H', size = 16)
```
:::
:::

## Basis 

:::{style="font-size: .8em"}
Since $\mathbf{a}_3$ is a scalar multiple of $\mathbf{a}_2,$ the most concise way of writing $H$ is

:::{.center-text style="font-size: 1em"}
$H=\text{Span}\{\mathbf{a}_1,\mathbf{a}_2\}$ or equivalently, $H=\text{Span}\{\mathbf{a}_1,\mathbf{a}_3\}.$
:::

In other words, $\{\mathbf{a}_1, \mathbf{a}_2\}$ forms a _**basis**_ for $H$ and so does $\{\mathbf{a}_1,\mathbf{a}_3\}$.

:::{.center-text}
```{python}
fig = ut.three_d_figure((7, 5), fig_desc = 'Bases of H are {a1, a2} or {a1, a3}.',
                        xmin = -10, xmax = 10, ymin = -10, ymax = 10, zmin = -10, zmax = 10, qr = qr_setting)
a1 = [-8.0, 8.0, 5.0]
a2 = [3.0,  2.0, -2.0]
a3 = 2.5 * np.array(a2)
fig.text(a1[0]+.5, a1[1]+.5, a1[2]+.5, r'$\bf a_1$', 'a_1', size=18)
fig.text(a3[0]+.5, a3[1]+.5, a3[2]+.5, r'$\bf a_3$', 'a_3', size=18)
fig.text(a2[0]+.5, a2[1]+.5, a2[2]+.5, r'$\bf a_2$', 'a_2', size=18)
fig.plotSpan(a1, a2,'Green')
fig.plotPoint(a1[0], a1[1], a1[2],'r')
fig.plotPoint(a3[0], a3[1], a3[2],'r')
fig.plotPoint(a2[0], a2[1], a2[2],'r')
fig.plotLine([[0, 0, 0], a3], 'r', '--')
fig.plotLine([[0, 0, 0], a1], 'r', '--')
# fig.plotPoint(a3[0], a3[1], a3[2],'r')
fig.text(0.1, 0.1, -3, r'$\bf 0$', '0', size=12)
fig.plotPoint(0, 0, 0, 'b')
fig.set_title(r'Bases of $H$ are $\{{\bf a}_1, {\bf a}_2\}$ or $\{{\bf a}_1, {\bf a}_3\}$')
fig.text(9, -9, -7, r'H', 'H', size = 16)
```
:::
:::

## Basis

:::{style="font-size: .8em"}

It can be shown that the smallest possible spanning set must be _**linearly independent**_.

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <span class="label">Basis for a vector space</span>
        <p>A <b>basis for a vector space</b>  \(V\) is a linearly independent set in \(V\) that spans \(V.\)</p>
    </div>
    """

html_content = generate_html()
display(HTML(html_content))
```

Similarly, a **basis for a subspace**  $H$ of $V$ is a linearly independent set in $H$ that spans $H.$

<br>

Note that in our example, $\{\mathbf{a}_1, \mathbf{a}_2, \mathbf{a}_3\}$ is not a basis for $H,$ because $\mathbf{a}_2$ and $\mathbf{a}_3$ are not linearly independent.
Furthermore, $\{\mathbf{a}_1\}$ is also not a basis for $H,$ because it does not span $H.$
:::

## Basis

:::{style="font-size: .7em"}
The columns of _**any**_ invertible $n\times n$ matrix form a basis for $\mathbb{R}^n,$ because, by the IMT, they are linearly independent and span $\mathbb{R}^n.$


```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <span class="label">Standard basis</span>
        <p>The <b>standard basis </b> for \(\mathbb{R}^n\) is the set \(\{\mathbf{e}_1,\dots,\mathbf{e}_n\}\), where vectors \(\mathbf{e}_1, \dots, \mathbf{e}_n,\) are the columns of the identity matrix \(I\).</p>
    </div>
    """
html_content = generate_html()
display(HTML(html_content))
```

:::{.center-text}
```{python}
fig = ut.three_d_figure((7, 6), fig_desc = 'The Standard Basis for R3',
                        xmin = -1.2, xmax = 1.2, ymin = -1.2, ymax = 1.2, zmin = -1.2, zmax = 1.2, qr = qr_setting)
e1 = [1, 0, 0]
e2 = [0, 1, 0]
e3 = [0, 0, 1]
origin = [0, 0, 0]
fig.ax.quiver(e1, e2, e3, e1, e2, e3, length=1.0, color='Red')
fig.plotLine([[0, 0, 0], [0, 1, 0]], color='Red')
fig.plotLine([[0, 0, 0], [0, 0, 1]], color='Red')
fig.plotLine([[0, 0, 0], [1, 0, 0]], color='Red')
fig.text(1, 0, -0.5, r'${\bf e_1}$', 'e1', size=16)
fig.text(0.2, 1, 0, r'${\bf e_2}$', 'e2', size=16)
fig.text(0, 0.2, 1, r'${\bf e_3}$', 'e3', size=16)
# plotting the axes
fig.plotIntersection([0, 0, 1, 0], [0, 1, 0, 0])
fig.plotIntersection([0, 0, 1, 0], [1, 0, 0, 0])
fig.plotIntersection([0, 1, 0, 0], [1, 0, 0, 0]);
```
:::
:::

## Dimension 

:::{style="font-size: .8em"}
If a vector space $V$ has a basis of $p$ vectors, then _**every**_ basis of $V$ must consist of exactly $p$ vectors. 
The same is true for a subspace $H$.

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
    <span class="label">Dimension</span>
        <p>The <b>dimension</b> of a vector (sub)space \(H,\) denoted by \(\dim H,\) is the number of vectors in any basis for \(H.\)</p>
    </div>
    """

html_content = generate_html()
display(HTML(html_content))
```
__Remark__: The dimension of the zero subspace $\{{\bf 0}\}$ is defined to be zero.  

For example, a plane through the origin ${\bf 0}$ is two-dimensional, and a line through ${\bf 0}$ is one-dimensional.

:::

## Basis for a Nullspace

:::{style="font-size: .8em"}
__Example__.
We are going to find a basis for the null space of the matrix
:::
:::{style="font-size: .6em"}
$$
A = \begin{bmatrix}-3&6&-1&1&-7\\1&-2&2&3&-1\\2&-4&5&8&-4\end{bmatrix}.
$$
:::

:::{style="font-size: .8em"}
We need to describe the set of all solutions of $A\mathbf{x} = {\bf 0}.$

We start by performing Gaussian elimination on the augmented matrix:
:::

:::{style="font-size: .6em"}
$$
\left[ \begin{array}{c|c} A & {\bf 0} \end{array}\right] \sim \left[\begin{array}{ccccc|c}1&-2&0&-1&3&0\\0&0&1&2&-2&0\\0&0&0&0&0&0\end{array}\right], \;\;\;
\begin{array}{rrrrrcl}x_1&-2x_2&&-x_4&+3x_5&=&0\\&&x_3&+2x_4&-2x_5&=&0\\&&&&0&=&0\end{array}
$$
:::

:::{style="font-size: .8em"}
$x_1$ and $x_3$ are basic variables, and $x_2, x_4,$ and $x_5$ are free variables.
:::

## Basis for a Nullspace

:::{style="font-size: .8em"}
__Example (continued)__.
So the general solution is:

$$
\begin{array}{rcl}x_1&=&2x_2 + x_4 -3x_5,\\
x_3&=&-2x_4 + 2x_5.\end{array}
$$

Now, what we write the solution set as a _**weighted combination of vectors**_, or simply a vector equation.

The key idea is that the _**free variables will become the weights**_.
:::

## Basis for a Nullspace

:::{style="font-size: .6em"}
$$
\begin{aligned}
\begin{bmatrix}x_1\\x_2\\x_3\\x_4\\x_5\end{bmatrix} 
&= \begin{bmatrix}2x_2 + x_4 - 3x_5\\x_2\\-2x_4 + 2x_5\\x_4\\x_5\end{bmatrix} \\
&= x_2\begin{bmatrix}2\\1\\0\\0\\0\end{bmatrix} 
+ x_4\begin{bmatrix}1\\0\\-2\\1\\0\end{bmatrix} 
+ x_5\begin{bmatrix}-3\\0\\2\\0\\1\end{bmatrix} \\
&= x_2\mathbf{u} + x_4\mathbf{v} + x_5\mathbf{w}.
\end{aligned}
$$
:::

:::{style="font-size: .8em"}
This expression describes the entire solution set of $A\mathbf{x} = {\bf 0}.$ <br>
Hence, ${\operatorname{Nul}}\ A$ is the set of all linear combinations of $\mathbf{u}, \mathbf{v},$ and ${\bf w}$.  That is, ${\operatorname{Nul}}\ A$ is the subspace _**spanned**_ by $\{\mathbf{u}, \mathbf{v}, {\bf w}\}.$
:::

## Basis for a Nullspace

:::{style="font-size: .8em"}
__Example (continued)__.
Note that each vector has a unique pattern of non-zero entries and each weight appears only in one position. 
Hence, this construction automatically makes $\mathbf{u}, \mathbf{v},$ and ${\bf w}$ _**linearly independent**_.  

Thus, $\{\mathbf{u}, \mathbf{v}, {\bf w}\}$ is a _**basis**_ for ${\operatorname{Nul}}\ A.$

<!-- Conclusion: by finding a parametric description of the solution of the equation $A\mathbf{x} = {\bf 0},$ we can construct a basis for the nullspace of $A$. -->


```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>What is the dimension of \(\operatorname{Nul} A\)?</p>
    </div>
    """

html_content = generate_html()
display(HTML(html_content))
```

:::

:::{.notes}
It is 3. To find the dimension of $\operatorname{Nul} A$, we can count the number of free variables in RREF.
:::

## Basis for a Column Space

:::{style="font-size: .8em"}
Since a basis for the column space must span it, we can use all matrix columns as our starting point. How do we select from all columns the linearly independent ones?

__Example__. Suppose we have a matrix $B$ that happens to be in _reduced echelon form:_

$$
B = \begin{bmatrix}1&0&-3&5&0\\0&1&2&-1&0\\0&0&0&0&1\\0&0&0&0&0\end{bmatrix}.
$$

Denote the columns by $\mathbf{b}_1,\dots,\mathbf{b}_5$.
Then $\mathbf{b}_3 = -3\mathbf{b}_1 + 2\mathbf{b}_2$ and $\mathbf{b}_4 = 5\mathbf{b}_1-\mathbf{b}_2.$ Hence, any combination of $\mathbf{b}_1,\dots,\mathbf{b}_5$ is actually just a combination of $\mathbf{b}_1, \mathbf{b}_2,$ and $\mathbf{b}_5.$
:::

## Basis of a Column Space

:::{style="font-size: .8em"}
That is, $\{\mathbf{b}_1, \mathbf{b}_2, \mathbf{b}_5\}$ spans ${\operatorname{Col}}\ B$.

Furthermore, $\mathbf{b}_1, \mathbf{b}_2,$ and $\mathbf{b}_5$ are also linearly independent, because they are a subset of columns of a $4 \times 4$ identity matrix.

We conclude that the pivot columns of $B$ form a basis for $\operatorname{Col} B.$

:::{.fragment}
In general, _for matrices in reduced row echelon form_, we have a simple rule for the basis of the column space:
    
> Choose the columns that hold the pivots, or in other words the columns corresponding to the _basic variables_.

Hopefully now the term "basic variable" makes sense!
:::
:::

## Basis of a Column Space

:::{style="font-size: .8em"}
This idea generalizes even to matrices that aren't in reduced echelon form: the pivot columns of $A$ form a basis for ${\operatorname{Col}}\ A$ _for any_ $A$.
<br>

Suppose that $A\mathbf{x} = {\bf 0}$ for some nonzero vector $\mathbf{x}$. This says that there is a linear dependence relation between some of the columns of $A$.

If any of the entries in $\mathbf{x}$ are zero, then those columns do not participate in the linear dependence relation.

<!-- When we row-reduce $A$ to its reduced echelon form $B$, the columns are changed, but the equations $A\mathbf{x} = {\bf 0}$ and $B\mathbf{x} = {\bf 0}$ have the same solution set.   -->
<!-- :::

## Basis of a Column Space

:::{style="font-size: .8em"} -->
<!-- The columns of $A$ and the columns of $B$ _have exactly the same dependence relationships_ as the columns of $B$.

Specifically:

1. If some set of columns of $B$ spans the column space of $B$ (meaning that the remaining columns can be written as a linear combination of the columns in the span), then the same columns of $A$ span the column space of $A$.

2. If some set of columns of $B$ are linearly independent (meaning that no non-zero combination of these columns yields the zero vector), then the same columns of $A$ are linearly independent. -->

When we row-reduce $A$ to its reduced echelon form $B$, the columns are changed, but the equations $A\mathbf{x} = {\bf 0}$ and $B\mathbf{x} = {\bf 0}$ have the same solution set.  

In other words:

> If some columns of $B$ are a basis for ${\operatorname{Col}}\ B$, then the corresponding columns of $A$ are a basis for ${\operatorname{Col}}\ A$.
:::

## Basis of a Column Space

:::{style="font-size: .8em"}
__Example__.
Consider matrix $A$:
:::

:::{style="font-size: .65em"}
$$
A = \begin{bmatrix}1&3&3&2&-9\\-2&-2&2&-8&2\\2&3&0&7&1\\3&4&-1&11&-8\end{bmatrix}
$$
:::

:::{style="font-size: .8em"}
Matrix $B$ that we considered in the previous example is the RREF of $A$. Recall that a basis for ${\operatorname{Col}}\ B$ was columns 1, 2, and 5.

So a basis for ${\operatorname{Col}}\ A$ is formed by the corresponding columns of $A$:
:::
:::{style="font-size: .65em"}
$$
\left\{\begin{bmatrix}1\\-2\\2\\3\end{bmatrix},\begin{bmatrix}3\\-2\\3\\4\end{bmatrix},\begin{bmatrix}-9\\2\\1\\-8\end{bmatrix}\right\}.
$$
:::

## Matrix Rank

:::{style="font-size: .8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
    <span class="label">Theorem </span>
        <p>The pivot columns of matrix \(A\) form a basis for the column space of \(A\).</p>
    </div>
    """

html_content = generate_html()
display(HTML(html_content))
```

<br>

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
    <span class="label">Matrix rank </span>
        <p>The <b>rank</b> of a matrix, denoted by \(\operatorname{Rank}A\), is the dimension of the column space of \(A\).</p>
    </div>
    """

html_content = generate_html()
display(HTML(html_content))
```


Since the pivot columns of $A$ form a basis for $\operatorname{Col} A,$ the rank of $A$ is just the number of pivot columns in $A$. 

In other words, the rank of $A$ is the number of basic variables in a linear system of the form $A {\bf x} = {\bf b}$.
:::

## Matrix Rank

:::{style="font-size: .8em"}
For matrices $A$ and $B$ of appropriate sizes it can be shown that<br>

1. $\small \operatorname{Rank}(A + B)\leq \operatorname{Rank} A + \operatorname{Rank}(B).$
2. $\small \operatorname{Rank}(A B)\leq \min(\operatorname{Rank}A,\operatorname{Rank}B).$

```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="blue-box">
        <p>Let \(A = \begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix}\) and  \(B = \begin{bmatrix} 2 & 1 & 4 \\ 3 & 1.5 & 6 \end{bmatrix}.\) <br>
        1. What is the rank of A?<br>
        2. What is the rank of B?<br>
        3. What is the rank of AB?<br>
        </p>
    </div>
    """

html_content = generate_html()
display(HTML(html_content))
```

:::


## Matrix Rank

:::{style="font-size: .8em"}
__Example__.
Determine the rank of the matrix
:::
:::{style="font-size: .7em"}
$$
A = \begin{bmatrix}2&5&-3&-4&8\\4&7&-4&-3&9\\6&9&-5&2&4\\0&-9&6&5&-6\end{bmatrix}.
$$
:::
:::{style="font-size: .8em"}
Reduce $A$ to an echelon form. One result is:
:::
:::{style="font-size: .7em"}
$$
\begin{bmatrix}\fbox{2}&5&-3&-4&8\\0&\fbox{-3}&2&5&-7\\0&0&0&\fbox{4}&-6\\0&0&0&0&0\end{bmatrix}.
$$
:::
:::{style="font-size: .8em"}
Hence the matrix $A$ has 3 pivot columns, so $\operatorname{Rank} A = 3.$
:::

## Rank-Nullity Theorem

:::{style="font-size: .8em"}
Consider a matrix $A$ with  $n$ columns. 

-  $\dim\operatorname{Nul}\ A$ = the number of free variables in $A\mathbf{x} = {\bf 0}$,  which is the number of non-pivot columns in $A$.

- $\dim\operatorname{Col}\ A$ = the number of basis variables in $A\mathbf{x} = {\bf 0}$, which is the number of pivot columns.

So we can now make this important connection:
:::
:::{style="font-size: .6em"}
$$
\begin{array}{rcl}
\dim\operatorname{Nul}\ A + \dim\operatorname{Col}\ A &= &\mbox{number of non-pivot columns of $A$ + number of pivot columns of $A$}\\
&= &\mbox{number of columns of $A$}.
\end{array}
$$
:::
:::{style="font-size: .8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
    <span class="label">Theorem </span>
        <p>If a matrix \(A\) has \(n\) columns, then \(n=\operatorname{Rank} A + \dim\operatorname{Nul}\).</p>
    </div>
    """

html_content = generate_html()
display(HTML(html_content))
```
:::
<!-- :::{style="font-size: .8em"}
This relationship involving dimension is true even though the two subspaces themselves live in different spaces: $\operatorname{Nul}\ A \subset \mathbb{R}^n$ and $\operatorname{Col}\ A \subset \mathbb{R}^m$.
::: -->

<!-- ## Rank-Nullity Theorem

:::{style="font-size: .8em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
        <p>If a matrix \(A\) has \(n\) columns, then \(\operatorname{Rank} A + \dim\operatorname{Nul}\).</p>
    </div>
    """

html_content = generate_html()
display(HTML(html_content))
```

Let's think about a matrix $A$ and the associated linear transformation $T(x) = Ax$.

- If matrix $A$ has $n$ columns, $A$'s column space _could_ have a dimension as high as $n$. Equivalently, $T$'s range _could_ have dimension as high as $n$.

- _However,_ if $A$ "throws away" a nullspace of dimension $p$, it _reduces_ the column space of $A$ to $n-p$. Meaning, the dimension of $T$'s range is reduced to $n-p$.
::: -->

## Extending the Invertible Matrix Theorem{.really-smaller-title}

:::{style="font-size: 1em"}
<!-- The above arguments show that when $A$ has $n$ columns, then the "larger" that the column space is, the "smaller" that the null space is.  -->

Let's consider what this means when $A$ is a square $n\times n$ matrix.

- On one "extreme," the column space of $A$ could have maximum dimension -- i.e., $\dim\operatorname{Col}\ A= n.$

- Recall that the IMT said that an $n\times n$ matrix is invertible if and only if its columns are linearly independent, and if and only if its columns span $\mathbb{R}^n$.

We can now see that an $n\times n$ matrix is invertible if and only if the columns of $A$ form a basis for $\mathbb{R}^n.$
:::

## Extending the Invertible Matrix Theorem{.really-smaller-title}

:::{style="font-size: 1em"}
```{python}
from IPython.core.display import HTML

def generate_html():
    return r"""
    <div class="purple-box">
    <span class="label">Theorem </span>
        <p>Let \(A\) be a square \(n\times n\) matrix.  Then the following statements are each equivalent to the statement that \(A\) is an invertible matrix:
        <ol start="1">
        <li>The columns of \(A\) form a basis for \(\mathbb{R}^n.\)</li>
        <li>\(\operatorname{Col} A = \mathbb{R}^n.\)</li>
        <li>\(\dim\operatorname{Col} A = n.\)</li>
        <li>\(\operatorname{Rank} A = n.\)</li>
        <li>\(\operatorname{Nul} A = \{{\bf 0}\}.\)</li>
        <li>\(\dim\operatorname{Nul} A = 0.\)</li>
        </p>
    </div>
    """

html_content = generate_html()
display(HTML(html_content))
```
:::